Repository team-confeti/confeti-client, pull requests merged in 2025-05, with the labels that each got.

#501 Fix(design-system): (QA/5) 음악 아이템 아티스트 제목의 최대 너비 및 너비 설정 추가
  packages/design-system/src/components/music-item/music-item.css.ts
Labels: 지욱 🥁, 🎨 Style

#506 Feat(client): Type-Safe 라우팅을 위한 buildPath 유틸함수 생성
  .vscode/settings.json
  apps/client/src/pages/login/hooks/use-social-login-mutation.ts
  apps/client/src/pages/login/page/login.tsx
  apps/client/src/pages/my-history/components/add-setlist/setlist-performance.tsx
  apps/client/src/pages/my-history/components/preview/preview-section.tsx
  apps/client/src/pages/my-history/components/setlist-detail/setlist-empty.tsx
  apps/client/src/pages/my-history/page/add-songs/confirm-add-section.tsx
  apps/client/src/pages/my-history/page/my-history.tsx
  apps/client/src/pages/my-history/page/record/my-record.tsx
  apps/client/src/pages/my-history/page/setlist-detail/setlist-detail.tsx
  apps/client/src/pages/my/components/artist/no-artist-section.tsx
  apps/client/src/pages/my/components/profile/user-info.tsx
  apps/client/src/pages/my/components/upcoming-performance/upcoming-performance-section.tsx
  apps/client/src/pages/my/hooks/use-delete-account.ts
  apps/client/src/pages/my/hooks/use-logout.ts
  apps/client/src/pages/my/page/profile/my-profile.tsx
  apps/client/src/pages/my/page/setting/setting.tsx
  apps/client/src/pages/onboarding/page/onboarding.tsx
  apps/client/src/pages/search/components/search-home/recent-search-section.tsx
  apps/client/src/pages/time-table/components/empty/empty-festival-section.tsx
  apps/client/src/pages/time-table/components/festival-selector/festival-selector.tsx
  apps/client/src/pages/time-table/page/add-festival/add-festival.tsx
  apps/client/src/pages/time-table/page/time-table-layout.tsx
  apps/client/src/shared/apis/config/interceptor.ts
  apps/client/src/shared/components/navigation-tabs.tsx
  apps/client/src/shared/hooks/use-navigate-to-detail.ts
  apps/client/src/shared/pages/auth/require-login-section.tsx
  apps/client/src/shared/router/path.ts
  apps/client/src/shared/router/router.tsx
  apps/client/src/shared/types/home-response.ts
  apps/client/src/shared/types/search-reponse.ts
  apps/client/src/shared/types/user-response.ts
  apps/client/src/shared/utils/build-path.ts
Labels: ✨ Feature, 🛠️ Refactor, 민하 🎸

#512 Fix(client): 헤더 스타일 및 시간 아이콘 수정
  packages/design-system/src/components/header/header.css.ts
  packages/design-system/src/components/header/header.tsx
  packages/design-system/src/icons/assets/btn_account_gray_28.svg
  packages/design-system/src/icons/assets/ic_new_search_28.svg
  packages/design-system/src/icons/assets/ic_time_gray_14.svg
  packages/design-system/src/icons/src/BtnAccountGray28.tsx
  packages/design-system/src/icons/src/IcNewSearch28.tsx
  packages/design-system/src/icons/src/IcTimeGray14.tsx
  packages/design-system/src/icons/src/index.ts
Labels: 다현 🎧, 🎨 Style

#515 Feat(client): UI 관련 QA 반영
  apps/client/src/pages/my-history/components/add-setlist/setlist-performance.css.ts
  apps/client/src/pages/my-history/components/record/record-info.tsx
  apps/client/src/pages/my-history/components/record/record-introduce.tsx
  apps/client/src/pages/my/components/profile/user-info.css.ts
  apps/client/src/pages/my/components/profile/user-info.tsx
  apps/client/src/pages/onboarding/components/artist-select.css.ts
  apps/client/src/pages/performance/components/reservation/reservation.css.ts
  apps/client/src/pages/time-table/page/delete-festival/delete-festival-dialogs.tsx
  packages/design-system/src/components/avatar/avatar.css.ts
  packages/design-system/src/components/avatar/avatar.tsx
  packages/design-system/src/components/footer/footer.tsx
  packages/design-system/src/components/performance-carousel/performance-carousel.css.ts
Labels: 다현 🎧, 🎨 Style

#519 Refactor: Rendering block 현상 해결 및 이미지 cdn 구축, lazy loading 재적용
  apps/client/index.html
  apps/client/public/images/confeti_3d_logo21.svg
  apps/client/src/App.tsx
  apps/client/src/pages/home/components/performance-carousel-section.tsx
  apps/client/src/pages/home/components/suggest-performance-section.tsx
  apps/client/src/pages/home/page/home-page.tsx
  apps/client/src/pages/login/page/login.css.ts
  apps/client/src/pages/login/page/login.tsx
  apps/client/src/pages/onboarding/components/onboarding-complete.css.ts
  apps/client/src/pages/onboarding/components/onboarding-complete.tsx
  apps/client/src/pages/time-table/page/time-table-page.tsx
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/router/lazy.ts
  apps/client/src/shared/router/router.tsx
  apps/client/src/shared/utils/convert-to-cdn-url.ts
  packages/design-system/package.json
  packages/design-system/src/components/button-icon/button-icon.tsx
  packages/design-system/src/components/performance-carousel/performance-carousel.css.ts
  packages/design-system/src/icons/src/Confeti3DLogo21.tsx
  packages/design-system/src/icons/src/index.ts
  packages/design-system/src/styles/font/font.css
  packages/design-system/src/styles/global.css.ts
  pnpm-lock.yaml
Labels: 🛠️ Refactor, 한서 🎤

#518 Fix(client): 내 공연 관련 버그 수정
  apps/client/src/pages/my-history/components/add-setlist/setlist-performance.tsx
  apps/client/src/pages/my-history/components/preview/preview-section.tsx
  apps/client/src/pages/my-history/components/setlist-detail/setlist-empty.tsx
  apps/client/src/pages/my-history/components/setlist-detail/setlist-tracks.tsx
  apps/client/src/pages/my-history/page/add-songs/confirm-add-section.tsx
  apps/client/src/pages/my-history/page/overview/my-history-overview-page.tsx
  apps/client/src/pages/my-history/page/setlist-detail/setlist-detail.tsx
  apps/client/src/shared/router/path.ts
  apps/client/src/shared/types/my-history-response.ts
  packages/design-system/src/components/festival-card/festival-card.tsx
Labels: 👾 Fix, 민하 🎸

#528 Fix(client): 페스티벌 추가 갯수 수정 및 toast 이벤트 수정
  apps/client/src/pages/time-table/constants/index.ts
  apps/client/src/pages/time-table/page/add-festival/add-festival.tsx
Labels: 👾 Fix, 지욱 🥁

#531 Feat(client): SwitchCase 컴포넌트 제작
  apps/client/src/pages/my-history/page/add-setlist/add-setlist-page.tsx
  apps/client/src/pages/onboarding/components/onboarding-complete.tsx
  apps/client/src/pages/search/page/search-page.tsx
  apps/client/src/shared/components/switch-case.tsx
Labels: ✨ Feature, 민하 🎸

#534 Feat(client): 로그인 로직 개선
  apps/client/.env.example
  apps/client/src/App.tsx
  apps/client/src/pages/auth/hooks/use-social-login-mutation.ts
  apps/client/src/pages/auth/page/login-page.css.ts
  apps/client/src/pages/auth/page/login-page.tsx
  apps/client/src/pages/auth/page/redirect-kakao.tsx
  apps/client/src/pages/auth/page/require-login.tsx
  apps/client/src/pages/auth/utils/apple-login.ts
  apps/client/src/pages/home/page/home-page.tsx
  apps/client/src/pages/login/hooks/use-social-login-mutation.ts
  apps/client/src/shared/apis/auth/auth.ts
  apps/client/src/shared/apis/config/instance.ts
  apps/client/src/shared/apis/config/interceptor.ts
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/constants/config.ts
  apps/client/src/shared/constants/user-constants.ts
  apps/client/src/shared/router/lazy.ts
  apps/client/src/shared/router/path.ts
  apps/client/src/shared/router/router.tsx
  apps/client/src/shared/utils/check-is-not-logged-in.ts
  apps/client/src/shared/utils/convert-to-cdn-url.ts
  apps/client/src/shared/utils/token-handler.ts
Labels: ✨ Feature, 민하 🎸

#537 Feat(client): 추천 음악 정지 기능 추가
  apps/client/src/pages/home/components/suggest-music-section.tsx
  apps/client/src/shared/hooks/use-music-player.ts
Labels: ✨ Feature, 지욱 🥁
