Repository team-confeti/confeti-client, pull requests merged in 2025-02, with the labels that each got.

#301 Refactor(client): confeti관련 파일명 및 import 경로 수정
  apps/client/src/App.tsx
  apps/client/src/pages/home/page/home.tsx
  apps/client/src/pages/my/components/artist/artist-section.tsx
  apps/client/src/pages/my/components/artist/no-artist-section.tsx
  apps/client/src/pages/my/components/performance/no-performance-section.css.ts
  apps/client/src/pages/my/components/performance/no-performance-section.tsx
  apps/client/src/pages/my/components/performance/performance-section.css.ts
  apps/client/src/pages/my/components/performance/performance-section.tsx
  apps/client/src/pages/my/components/profile/logout-button.tsx
  apps/client/src/pages/my/components/profile/user-info.css.ts
  apps/client/src/pages/my/page/artist/artist-more.tsx
  apps/client/src/pages/my/page/performance/performance-more.css.ts
  apps/client/src/pages/my/page/performance/performance-more.tsx
  apps/client/src/pages/my/page/profile/my-profile.tsx
  apps/client/src/pages/performance/components/artist/artist-card.css.ts
  apps/client/src/pages/performance/components/artist/artist-card.tsx
  apps/client/src/pages/performance/components/artist/artist-grid.css.ts
  apps/client/src/pages/performance/components/artist/artist-grid.tsx
  apps/client/src/pages/performance/components/artist/artist-section.css.ts
  apps/client/src/pages/performance/components/artist/artist-section.tsx
  apps/client/src/pages/performance/components/artist/artist-title.css.ts
  apps/client/src/pages/performance/components/artist/artist-title.tsx
  apps/client/src/pages/performance/components/button/more-button.css.ts
  apps/client/src/pages/performance/components/button/more-button.tsx
  apps/client/src/pages/performance/components/expanded/expanded-section.css.ts
  apps/client/src/pages/performance/components/expanded/expanded-section.tsx
  apps/client/src/pages/performance/components/info/info.css.ts
  apps/client/src/pages/performance/components/info/info.tsx
  apps/client/src/pages/performance/components/performance/performance-detail.css.ts
  apps/client/src/pages/performance/components/performance/performance-detail.tsx
  apps/client/src/pages/performance/components/poster/poster.css.ts
  apps/client/src/pages/performance/components/poster/poster.tsx
  apps/client/src/pages/performance/components/summary/summary.css.ts
  apps/client/src/pages/performance/components/summary/summary.tsx
  apps/client/src/pages/performance/constant/performance.ts
  apps/client/src/pages/performance/hooks/use-concert-detail.ts
  apps/client/src/pages/performance/hooks/use-festival-detail.ts
  apps/client/src/pages/performance/page/concert-detail.tsx
  apps/client/src/pages/performance/page/festival-detail.tsx
  apps/client/src/pages/performance/types/artist.ts
  apps/client/src/pages/performance/types/concert.ts
  apps/client/src/pages/performance/types/festival.ts
  apps/client/src/shared/apis/confeti-detail/performance-queries.ts
  apps/client/src/shared/apis/confeti-detail/performance.ts
  apps/client/src/shared/router/lazy.ts
Labels: 🛠️ Refactor, 민하 🎸

#303 Refactor(client): 상세 페이지 플로팅 버튼 UX 개선
  apps/client/src/pages/performance/page/concert-detail.tsx
  apps/client/src/pages/performance/page/festival-detail.tsx
  apps/client/src/pages/time-table/components/edit/edit-floating-button.tsx
  apps/client/src/pages/time-table/components/info/info-button.tsx
  apps/client/src/pages/time-table/hooks/use-scroll-position.ts
  apps/client/src/shared/hooks/use-scroll-position.ts
  packages/design-system/src/components/floating-button/floating-button.css.ts
  packages/design-system/src/components/floating-button/floating-button.tsx
Labels: ✨ Feature, 🛠️ Refactor, 지욱 🥁

#305 Docs(design-system): CSS 스타일 수정 및 스토리북 데이터 업데이트
  packages/design-system/src/components/artist-card/artist-card.css.ts
  packages/design-system/src/components/artist-card/artist-card.stories.tsx
  packages/design-system/src/components/festival-card/festival-card.stories.tsx
  packages/design-system/src/components/floating-button/floating-button.css.ts
  packages/design-system/src/components/floating-button/floating-button.stories.tsx
  packages/design-system/src/components/like-button/like-button.stories.tsx
  packages/design-system/src/components/performance-carousel/performance-carousel.stories.tsx
  packages/design-system/src/components/performance-carousel/performance-carousel.tsx
Labels: 📑 Docs, 지욱 🥁
