Repository team-confeti/confeti-client, pull requests merged in 2025-04, with the labels that each got.

#345 Feat(design-system): DropdownMenu 컴포넌트 구현
  apps/client/src/pages/home/page/home.css.ts
  apps/client/tsconfig.json
  packages/design-system/src/components/dropdown-menu/dropdown-menu.css.ts
  packages/design-system/src/components/dropdown-menu/dropdown-menu.stories.tsx
  packages/design-system/src/components/dropdown-menu/dropdown-menu.tsx
  packages/design-system/src/components/index.ts
  packages/design-system/src/components/performance-carousel/performance-carousel.tsx
  packages/design-system/src/hooks/use-click-outside.ts
  packages/design-system/src/icons/assets/btn_meatball.svg
  packages/design-system/src/icons/assets/ic_timetable_addfestival.svg
  packages/design-system/src/icons/assets/ic_timetable_deletefestival.svg
  packages/design-system/src/icons/src/BtnMeatball.tsx
  packages/design-system/src/icons/src/IcTimetableAddfestival.tsx
  packages/design-system/src/icons/src/IcTimetableDeletefestival.tsx
  packages/design-system/src/icons/src/IcToastInfo24.tsx
  packages/design-system/src/icons/src/InfoOverlay.tsx
  packages/design-system/src/icons/src/SlideOverlayOp.tsx
  packages/design-system/src/icons/src/index.ts
  packages/design-system/src/styles/tokens/box-shadow.ts
  packages/design-system/src/styles/tokens/z-index.ts
Labels: ✨ Feature, 한서 🎤

#350 Feat(design-system): 버튼아이콘 컴포넌트 구현
  packages/design-system/package.json
  packages/design-system/src/components/button-icon/button-icon.stories.tsx
  packages/design-system/src/components/button-icon/button-icon.tsx
  packages/design-system/src/icons/assets/btn_download.svg
  packages/design-system/src/icons/src/BtnDownload.tsx
  packages/design-system/src/icons/src/index.ts
  pnpm-lock.yaml
Labels: ✨ Feature, 채은 🪕

#338 Feat(design-system): Chip 컴포넌트 구현
  packages/design-system/src/components/chip/chip.css.ts
  packages/design-system/src/components/chip/chip.stories.tsx
  packages/design-system/src/components/chip/chip.tsx
  packages/design-system/src/icons/assets/btn_search_delete.svg
  packages/design-system/src/icons/src/BtnSearchDelete.tsx
  packages/design-system/src/icons/src/index.ts
  packages/design-system/src/styles/tokens/border.ts
Labels: ✨ Feature, 다현 🎧

#362 Feat(client): MyArtist 페이지 수정된 뷰 적용
  apps/client/src/pages/my/components/artist/artist-list.css.ts
  apps/client/src/pages/my/components/artist/artist-list.tsx
  apps/client/src/pages/my/components/profile/box.css.ts
  apps/client/src/pages/my/components/profile/logout-button.css.ts
  apps/client/src/pages/my/components/profile/logout-button.tsx
  apps/client/src/pages/my/components/profile/logout-section.css.ts
  apps/client/src/pages/my/components/profile/logout-section.tsx
  apps/client/src/pages/my/components/profile/user-info.css.ts
  apps/client/src/pages/my/components/profile/user-info.tsx
  apps/client/src/pages/my/page/artist/artist-more.css.ts
  apps/client/src/pages/my/page/artist/artist-more.tsx
  apps/client/src/pages/my/page/profile/my-profile.tsx
  apps/client/src/shared/mocks/artists-data.ts
  apps/client/src/shared/types/login-response.ts
  apps/client/src/shared/types/user-response.ts
  packages/design-system/src/components/button/button.css.ts
  packages/design-system/src/components/button/button.stories.tsx
  packages/design-system/src/components/button/button.tsx
  packages/design-system/src/icons/assets/ic_switch.svg
  packages/design-system/src/icons/src/IcSwitch.tsx
  packages/design-system/src/icons/src/index.ts
  packages/design-system/src/styles/tokens/font-styles.ts
  packages/design-system/src/styles/tokens/typography.ts
Labels: ✨ Feature, 민하 🎸

#363 Refactor(client): 공연 상세보기 아티스트 섹션 수정
  apps/client/src/pages/performance/components/artist/artist-section.css.ts
  apps/client/src/pages/performance/components/artist/artist-section.tsx
  apps/client/src/pages/performance/components/artist/artist-title.css.ts
  apps/client/src/pages/performance/components/button/more-button.css.ts
  apps/client/src/pages/performance/components/expanded/expanded-section.css.ts
  packages/design-system/src/icons/assets/ic_arrow_down_gray_16.svg
  packages/design-system/src/icons/assets/ic_arrow_up_gray_16.svg
  packages/design-system/src/icons/src/IcArrowDownGray16.tsx
  packages/design-system/src/icons/src/IcArrowUpGray16.tsx
Labels: 🛠️ Refactor, 채은 🪕

#360 Feat(design-system): Dialog 컴포넌트 구현, OverlayProvider 추가
  apps/client/src/App.tsx
  apps/client/src/pages/home/page/home.tsx
  packages/design-system/.storybook/preview.tsx
  packages/design-system/src/components/button/button.css.ts
  packages/design-system/src/components/button/button.tsx
  packages/design-system/src/components/dialog/dialog.css.ts
  packages/design-system/src/components/dialog/dialog.stories.tsx
  packages/design-system/src/components/dialog/dialog.tsx
  packages/design-system/src/components/index.ts
  packages/design-system/src/components/themeProvider.tsx
  packages/design-system/src/context/overlay-context.tsx
  packages/design-system/src/icons/src/SlideOverlayOp.tsx
  packages/design-system/src/styles/theme.css.ts
  packages/design-system/src/styles/tokens/z-index.ts
Labels: ✨ Feature, 한서 🎤

#354 Feat(design-system): Music Item 및 List 컴포넌트 구현
  apps/client/src/pages/my/components/artist/artist-list.css.ts
  packages/design-system/src/components/music-item/music-item.css.ts
  packages/design-system/src/components/music-item/music-item.stories.tsx
  packages/design-system/src/components/music-item/music-item.tsx
  packages/design-system/src/components/music-list/music-list.stories.tsx
  packages/design-system/src/components/music-list/music-list.tsx
  packages/design-system/src/components/ticketing/ticketing-carousel.css.ts
  packages/design-system/src/icons/assets/btn_delete.svg
  packages/design-system/src/icons/assets/btn_delete_black.svg
  packages/design-system/src/icons/assets/ic_hamburger.svg
  packages/design-system/src/icons/assets/ic_pause.svg
  packages/design-system/src/icons/assets/ic_play.svg
  packages/design-system/src/icons/src/BtnDelete.tsx
  packages/design-system/src/icons/src/BtnDeleteBlack.tsx
  packages/design-system/src/icons/src/IcHamburger.tsx
  packages/design-system/src/icons/src/IcPause.tsx
  packages/design-system/src/icons/src/IcPlay.tsx
  packages/design-system/src/icons/src/index.ts
  packages/design-system/src/styles/tokens/display.ts
Labels: ✨ Feature, 다현 🎧

#368 Feat(client): MyConfeti 페이지 수정된 뷰 적용
  apps/client/src/pages/my/components/performance/performance-list.css.ts
  apps/client/src/pages/my/components/performance/performance-list.tsx
  apps/client/src/pages/my/components/profile/box.css.ts
  apps/client/src/pages/my/components/profile/box.tsx
  apps/client/src/pages/my/hooks/use-filter-performances.ts
  apps/client/src/pages/my/page/performance/performance-more.css.ts
  apps/client/src/pages/my/page/performance/performance-more.tsx
  packages/design-system/src/components/chip/chip.css.ts
  packages/design-system/src/components/index.ts
  packages/design-system/src/icons/assets/Info_overlay.svg
  packages/design-system/src/icons/assets/btn_delete.svg
  packages/design-system/src/icons/assets/btn_delete_black.svg
  packages/design-system/src/icons/assets/btn_delete_black_20.svg
  packages/design-system/src/icons/assets/btn_download.svg
  packages/design-system/src/icons/assets/btn_meatball.svg
  packages/design-system/src/icons/assets/btn_radio_active.svg
  packages/design-system/src/icons/assets/btn_radio_default.svg
  packages/design-system/src/icons/assets/btn_search_delete.svg
  packages/design-system/src/icons/assets/cmp_profile_non.svg
  packages/design-system/src/icons/assets/confeti_3d_logo2 1.svg
  packages/design-system/src/icons/assets/ic_arrow_down_gray_16.svg
  packages/design-system/src/icons/assets/ic_arrow_gray_16.svg
  packages/design-system/src/icons/assets/ic_arrow_up_gray_16.svg
  packages/design-system/src/icons/assets/ic_hamburger.svg
  packages/design-system/src/icons/assets/ic_new_search_gray_18.svg
  packages/design-system/src/icons/assets/ic_pause.svg
  packages/design-system/src/icons/assets/ic_play.svg
  packages/design-system/src/icons/assets/ic_settings_24.svg
  packages/design-system/src/icons/assets/ic_switch.svg
  packages/design-system/src/icons/assets/ic_time_gray_14.svg
  packages/design-system/src/icons/assets/ic_timetable_addfestival.svg
  packages/design-system/src/icons/assets/ic_timetable_deletefestival.svg
  packages/design-system/src/icons/assets/img_typelogo_big.svg
  packages/design-system/src/icons/assets/logo_footer.svg
  packages/design-system/src/icons/assets/slide_overlay_op.svg
  packages/design-system/src/icons/src/IcArrowGray16.tsx
  packages/design-system/src/icons/src/IcTimeGray14.tsx
  packages/design-system/src/icons/src/ImgTypelogoBig.tsx
  packages/design-system/src/icons/src/LogoFooter.tsx
Labels: ✨ Feature, 민하 🎸

#369 Feat(client): 온보딩 페이지 퍼블리싱
  apps/client/package.json
  apps/client/src/pages/onboarding/components/artist-select.css.ts
  apps/client/src/pages/onboarding/components/artist-select.tsx
  apps/client/src/pages/onboarding/components/onboarding-complete.css.ts
  apps/client/src/pages/onboarding/components/onboarding-complete.tsx
  apps/client/src/pages/onboarding/page/onboarding.tsx
  apps/client/src/pages/search/page/search.css.ts
  apps/client/src/pages/search/page/search.tsx
  apps/client/src/shared/assets/lotties/confeti-logo-animation.json
  apps/client/src/shared/pages/loading/loading.tsx
  apps/client/src/shared/router/lazy.ts
  apps/client/src/shared/router/router.tsx
  apps/client/src/shared/utils/use-funnel.tsx
  packages/design-system/src/components/description/description.css.ts
  packages/design-system/src/components/description/description.stories.tsx
  packages/design-system/src/components/description/description.tsx
  packages/design-system/src/components/index.ts
  packages/design-system/src/components/search-bar/search-bar.css.ts
  packages/design-system/src/components/search-bar/search-bar.tsx
  packages/design-system/src/icons/src/Confeti3DLogo21.tsx
  packages/design-system/src/styles/tokens/font-styles.ts
  pnpm-lock.yaml
Labels: ✨ Feature, 지욱 🥁

#370 Feat(client): 회원 탈퇴 페이지 구현, 탈퇴 api 연동 및 Amplitude 설정
  apps/client/.env.example
  apps/client/package.json
  apps/client/src/App.tsx
  apps/client/src/pages/my/hooks/use-delete-account.ts
  apps/client/src/pages/my/page/setting/delete-account.css.ts
  apps/client/src/pages/my/page/setting/delete-account.tsx
  apps/client/src/pages/my/page/setting/setting.css.ts
  apps/client/src/pages/my/page/setting/setting.tsx
  apps/client/src/shared/apis/auth/auth.ts
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/router/lazy.ts
  apps/client/src/shared/router/router.tsx
  packages/design-system/.storybook/preview.tsx
  packages/design-system/src/components/dialog/dialog.css.ts
  packages/design-system/src/components/dialog/dialog.tsx
  packages/design-system/src/components/themeProvider.tsx
  packages/design-system/src/styles/theme.css.ts
  pnpm-lock.yaml
Labels: ✨ Feature, 한서 🎤

#374 Feat(client): My 페이지 수정된 뷰 적용
  apps/client/src/pages/my/components/performance/performance-list.tsx
  apps/client/src/pages/my/components/profile/box.css.ts
  apps/client/src/pages/my/components/profile/box.tsx
  apps/client/src/pages/my/components/profile/user-info.css.ts
  apps/client/src/pages/my/components/upcomingPerformance/no-upcoming-performance-section.css.ts
  apps/client/src/pages/my/components/upcomingPerformance/no-upcoming-performance-section.tsx
  apps/client/src/pages/my/components/upcomingPerformance/upcoming-performance-section.css.ts
  apps/client/src/pages/my/components/upcomingPerformance/upcoming-performance-section.tsx
  apps/client/src/pages/my/page/profile/my-profile.tsx
  apps/client/src/shared/mocks/performance-data.ts
Labels: ✨ Feature, 민하 🎸

#377 Feat(client): 온보딩 페이지 내 검색 플로우 구현
  apps/client/src/pages/onboarding/components/artist-search.css.ts
  apps/client/src/pages/onboarding/components/artist-search.tsx
  apps/client/src/pages/onboarding/components/artist-select.tsx
  apps/client/src/pages/onboarding/components/onboarding-complete.tsx
  packages/design-system/src/components/avatar/avatar.css.ts
  packages/design-system/src/components/description/description.css.ts
Labels: ✨ Feature, 지욱 🥁

#378 Feat(client): 내 공연 초기페이지 뷰 제작
  apps/client/src/pages/home/constants/menu.ts
  apps/client/src/pages/home/page/home.tsx
  apps/client/src/pages/my-history/components/preview/preview-section.css.ts
  apps/client/src/pages/my-history/components/preview/preview-section.tsx
  apps/client/src/pages/my-history/components/record/record-info.css.ts
  apps/client/src/pages/my-history/components/record/record-info.tsx
  apps/client/src/pages/my-history/components/record/record-introduce.css.ts
  apps/client/src/pages/my-history/components/record/record-introduce.tsx
  apps/client/src/pages/my-history/page/my-history.tsx
  apps/client/src/pages/my-history/page/record/my-record.tsx
  apps/client/src/pages/my/page/profile/my-profile.tsx
  apps/client/src/pages/time-table/components/empty/empty-festival-section.tsx
  apps/client/src/pages/time-table/components/info/info-button.tsx
  apps/client/src/pages/time-table/page/time-table-layout.tsx
  apps/client/src/shared/components/navigation-tabs.tsx
  apps/client/src/shared/constants/path.ts
  apps/client/src/shared/router/lazy.ts
  apps/client/src/shared/router/router.tsx
  packages/design-system/src/components/box/box.css.ts
  packages/design-system/src/components/box/box.stories.tsx
  packages/design-system/src/components/box/box.tsx
  packages/design-system/src/components/index.ts
  packages/design-system/src/components/navigation/navigation.stories.tsx
  packages/design-system/turbo/generators/templates/component.hbs
  packages/design-system/turbo/generators/templates/stories.hbs
Labels: ✨ Feature, 민하 🎸

#379 Feat(Client): 검색 페이지 초기화면 뷰 퍼블리싱
  apps/client/src/pages/search/components/performance-section.tsx
  apps/client/src/pages/search/components/popular-search-section.css.ts
  apps/client/src/pages/search/components/popular-search-section.tsx
  apps/client/src/pages/search/components/recent-festivals-section.css.ts
  apps/client/src/pages/search/components/recent-festivals-section.tsx
  apps/client/src/pages/search/components/recent-search-section.css.ts
  apps/client/src/pages/search/components/recent-search-section.tsx
  apps/client/src/pages/search/mocks/search-data.ts
  apps/client/src/pages/search/mocks/searched-performance-data.ts
  apps/client/src/pages/search/page/search.css.ts
  apps/client/src/pages/search/page/search.tsx
  apps/client/src/shared/utils/limit-text-length.ts
  packages/design-system/src/components/chip/chip.css.ts
  packages/design-system/src/components/chip/chip.tsx
  packages/design-system/src/styles/tokens/display.ts
  packages/design-system/src/styles/tokens/font-styles.ts
  packages/design-system/src/styles/tokens/typography.ts
Labels: ✨ Feature, 다현 🎧

#384 Feat(client): 로그아웃 모달 추가
  apps/client/src/pages/my-history/page/record/my-record.tsx
  apps/client/src/pages/my/components/profile/logout-section.tsx
  apps/client/src/pages/my/page/setting/delete-account.tsx
  packages/design-system/src/components/index.ts
Labels: ✨ Feature, 민하 🎸

#385 Feat(client): 탑 100 아티스트 조회 api 연동
  .github/workflows/discord-notify.yml
  apps/client/src/pages/onboarding/components/artist-select.css.ts
  apps/client/src/pages/onboarding/components/artist-select.tsx
  apps/client/src/pages/onboarding/hooks/use-get-top-artist.ts
  apps/client/src/pages/onboarding/page/onboarding.tsx
  apps/client/src/shared/apis/onboard/top-artist-queries.ts
  apps/client/src/shared/apis/onboard/top-artist.ts
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/types/top-artist-response.ts
Labels: ✨ Feature, 지욱 🥁

#393 Feat(client): 다가오는 공연 조회 API 연동
  apps/client/src/pages/home/page/home.tsx
  apps/client/src/pages/my-history/page/my-history.tsx
  apps/client/src/pages/my-history/page/record/my-record.tsx
  apps/client/src/pages/my/components/performance/performance-list.css.ts
  apps/client/src/pages/my/components/performance/performance-list.tsx
  apps/client/src/pages/my/components/upcoming-performance/no-upcoming-performance-section.css.ts
  apps/client/src/pages/my/components/upcoming-performance/no-upcoming-performance-section.tsx
  apps/client/src/pages/my/components/upcoming-performance/upcoming-performance-section.css.ts
  apps/client/src/pages/my/components/upcoming-performance/upcoming-performance-section.tsx
  apps/client/src/pages/my/hooks/use-my-favorites.ts
  apps/client/src/pages/my/page/profile/my-profile.tsx
  apps/client/src/shared/apis/user/user-queries.ts
  apps/client/src/shared/apis/user/user.ts
  apps/client/src/shared/components/navigation-tabs.tsx
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/constants/path.ts
  apps/client/src/shared/hooks/use-navigate-to-detail.ts
  apps/client/src/shared/router/lazy.ts
  apps/client/src/shared/router/protected-route.tsx
  apps/client/src/shared/router/router.tsx
  apps/client/src/shared/router/scroll-to-top.tsx
  apps/client/src/shared/types/user-response.ts
  packages/design-system/src/components/button-icon/button-icon.tsx
  packages/design-system/src/components/button/button.tsx
  packages/design-system/src/components/dialog/dialog.tsx
  packages/design-system/src/components/header/header.css.ts
  packages/design-system/src/components/header/header.tsx
  packages/design-system/src/components/navigation/navigation.tsx
  packages/design-system/src/components/performance-carousel/performance-carousel.tsx
  packages/design-system/src/components/themeProvider.tsx
  packages/design-system/src/components/ticketing/ticketing-card.tsx
  packages/design-system/src/components/ticketing/ticketing-carousel.tsx
  packages/design-system/src/icons/assets/btn_settings_24.svg
  packages/design-system/src/icons/src/BtnSettings24.tsx
  packages/design-system/src/icons/src/index.ts
Labels: ✨ Feature, 민하 🎸

#394 Feat(client): My artist 전체 목록 조회 API 연결
  apps/client/src/pages/my/components/artist/artist-list.tsx
  apps/client/src/pages/my/hooks/use-my-favorites.ts
  apps/client/src/pages/my/page/artist/artist-more.tsx
  apps/client/src/pages/my/page/performance/performance-more.tsx
  apps/client/src/pages/my/page/profile/my-profile.tsx
  apps/client/src/shared/apis/user/user-queries.ts
  apps/client/src/shared/apis/user/user.ts
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/types/user-response.ts
  apps/client/src/shared/utils/format-date.ts
  packages/design-system/src/components/like-button/like-button.css.ts
  packages/design-system/src/components/like-button/like-button.tsx
Labels: ✨ Feature, 민하 🎸

#396 Feat(client): 로그인 여부에 따른 API 호출 방식 수정
  apps/client/src/App.tsx
  apps/client/src/pages/home/page/home.tsx
  apps/client/src/pages/login/hooks/use-social-login-mutation.ts
  apps/client/src/pages/login/page/login.tsx
  apps/client/src/pages/my/components/profile/logout-section.tsx
  apps/client/src/pages/my/hooks/use-logout.ts
  apps/client/src/shared/apis/auth/auth.ts
  apps/client/src/shared/apis/carousel/performances.ts
  apps/client/src/shared/apis/carousel/ticketing.ts
  apps/client/src/shared/apis/confeti-detail/performance.ts
  apps/client/src/shared/apis/config/instance.ts
  apps/client/src/shared/apis/config/interceptor.ts
  apps/client/src/shared/apis/onboard/artist-related-keywords.ts
  apps/client/src/shared/apis/onboard/top-artist.ts
  apps/client/src/shared/apis/search/search.ts
  apps/client/src/shared/constants/api.ts
  packages/design-system/src/components/performance-carousel/performance-carousel.css.ts
  packages/design-system/src/components/performance-carousel/performance-carousel.tsx
Labels: ✨ Feature, 민하 🎸

#398 Feat(client): 검색 로직 개선 및 아티스트 연관 검색어 조회 API 연동
  apps/client/src/pages/search/components/artist-section.css.ts
  apps/client/src/pages/search/components/artist-section.tsx
  apps/client/src/pages/search/components/performance-count-section.css.ts
  apps/client/src/pages/search/components/performance-count-section.tsx
  apps/client/src/pages/search/components/performance-info.tsx
  apps/client/src/pages/search/components/performance-section.tsx
  apps/client/src/pages/search/components/search-home/popular-search-section.css.ts
  apps/client/src/pages/search/components/search-home/popular-search-section.tsx
  apps/client/src/pages/search/components/search-home/recent-festivals-section.css.ts
  apps/client/src/pages/search/components/search-home/recent-festivals-section.tsx
  apps/client/src/pages/search/components/search-home/recent-search-section.css.ts
  apps/client/src/pages/search/components/search-home/recent-search-section.tsx
  apps/client/src/pages/search/components/search-result/artist/artist-info.css.ts
  apps/client/src/pages/search/components/search-result/artist/artist-info.tsx
  apps/client/src/pages/search/components/search-result/artist/artist-not-found.css.ts
  apps/client/src/pages/search/components/search-result/artist/artist-not-found.tsx
  apps/client/src/pages/search/components/search-result/artist/artist-section.tsx
  apps/client/src/pages/search/components/search-result/notice-section.css.ts
  apps/client/src/pages/search/components/search-result/notice-section.tsx
  apps/client/src/pages/search/components/search-result/performance/performance-info.css.ts
  apps/client/src/pages/search/components/search-result/performance/performance-info.tsx
  apps/client/src/pages/search/components/search-result/performance/performance-section.css.ts
  apps/client/src/pages/search/components/search-result/performance/performance-section.tsx
  apps/client/src/pages/search/components/search-result/title.css.ts
  apps/client/src/pages/search/components/search-result/title.tsx
  apps/client/src/pages/search/hooks/use-search-data.ts
  apps/client/src/pages/search/hooks/use-search-logic.ts
  apps/client/src/pages/search/page/search-page.css.ts
  apps/client/src/pages/search/page/search-page.tsx
  apps/client/src/pages/search/page/search-result-page.css.ts
  apps/client/src/pages/search/page/search-result-page.tsx
  apps/client/src/pages/search/page/search.tsx
  apps/client/src/shared/apis/search/search-queries.ts
  apps/client/src/shared/apis/search/search.ts
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/hooks/use-debounce-keyword.ts
  apps/client/src/shared/router/lazy.ts
  apps/client/src/shared/types/search-reponse.ts
  packages/design-system/src/components/search-bar/search-bar.tsx
  packages/design-system/src/components/search-suggestion-list/search-suggestion-list.tsx
  packages/design-system/src/icons/assets/btn_close.svg
  packages/design-system/src/icons/assets/ic_warning_60.svg
  packages/design-system/src/icons/src/BtnClose.tsx
  packages/design-system/src/icons/src/IcWarning60.tsx
  packages/design-system/src/icons/src/index.ts
Labels: ✨ Feature, 🛠️ Refactor, 민하 🎸

#400 Feat(client): 특정 아티스트와 관련된 아티스트 조회 기능 api 연동
  apps/client/src/pages/onboarding/components/artist-search.tsx
  apps/client/src/pages/onboarding/components/artist-select.css.ts
  apps/client/src/pages/onboarding/components/artist-select.tsx
  apps/client/src/pages/onboarding/constants/limit.ts
  apps/client/src/pages/onboarding/hooks/use-onboard.ts
  apps/client/src/pages/onboarding/page/onboarding.tsx
  apps/client/src/pages/search/page/search-page.tsx
  apps/client/src/shared/apis/onboard/artist-related-keywords-queries.ts
  apps/client/src/shared/apis/onboard/artist-related-keywords.ts
  apps/client/src/shared/apis/onboard/artist-related-queries.ts
  apps/client/src/shared/apis/onboard/artist-related.ts
  apps/client/src/shared/apis/onboard/top-artist-queries.ts
  apps/client/src/shared/apis/onboard/top-artist.ts
  apps/client/src/shared/constants/api.ts
  packages/design-system/src/components/avatar/avatar.css.ts
  packages/design-system/src/components/avatar/avatar.tsx
  packages/design-system/src/components/search-suggestion-list/search-suggestion-list.tsx
Labels: ✨ Feature, 지욱 🥁

#406 Feat(client): 온보딩 페이지 auth/onboard post api 연동
  apps/client/src/pages/onboarding/hooks/use-onboard.ts
  apps/client/src/pages/onboarding/page/onboarding.tsx
  apps/client/src/shared/apis/onboard/auth-onboard.ts
  apps/client/src/shared/constants/api.ts
Labels: ✨ Feature, 지욱 🥁

#411 Feat(client): 내 공연 타임테이블 전체보기 페이지 퍼블리싱 & api 연동
  apps/client/src/pages/my-history/components/overview/count-display.css.ts
  apps/client/src/pages/my-history/components/overview/count-display.tsx
  apps/client/src/pages/my-history/components/overview/order-by-button.css.ts
  apps/client/src/pages/my-history/components/overview/order-by-button.tsx
  apps/client/src/pages/my-history/components/preview/preview-section.tsx
  apps/client/src/pages/my-history/hooks/use-my-history.ts
  apps/client/src/pages/my-history/page/overview/my-history-overview-page.css.ts
  apps/client/src/pages/my-history/page/overview/my-history-overview-page.tsx
  apps/client/src/pages/my-history/page/record/my-record.tsx
  apps/client/src/pages/my/hooks/use-my-favorites.ts
  apps/client/src/pages/my/page/artist/artist-more.tsx
  apps/client/src/shared/apis/my-history/my-history-queries.ts
  apps/client/src/shared/apis/my-history/my-history.ts
  apps/client/src/shared/apis/user/user-queries.ts
  apps/client/src/shared/apis/user/user.ts
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/constants/path.ts
  apps/client/src/shared/constants/sort-label.ts
  apps/client/src/shared/router/lazy.ts
  apps/client/src/shared/router/router.tsx
  apps/client/src/shared/types/my-history-response.ts
  apps/client/src/shared/types/user-response.ts
  packages/design-system/src/icons/assets/btn_switch.svg
  packages/design-system/src/icons/src/BtnSwitch.tsx
  packages/design-system/src/icons/src/index.ts
Labels: ✨ Feature, 지욱 🥁

#410 Feat(client): 공연 연관 검색어 조회 API 연동
  apps/client/src/pages/onboarding/components/artist-search.tsx
  apps/client/src/pages/search/hooks/use-search-data.ts
  apps/client/src/pages/search/page/search-page.tsx
  apps/client/src/shared/apis/search/search-queries.ts
  apps/client/src/shared/apis/search/search.ts
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/types/search-reponse.ts
  packages/design-system/src/components/search-suggestion-list/search-suggestion-list.css.ts
  packages/design-system/src/components/search-suggestion-list/search-suggestion-list.tsx
  packages/design-system/src/icons/assets/cmp_search_artist_img.svg
  packages/design-system/src/icons/assets/cmp_search_img.svg
  packages/design-system/src/icons/src/CmpSearchArtistImg.tsx
  packages/design-system/src/icons/src/CmpSearchImg.tsx
  packages/design-system/src/icons/src/index.ts
Labels: ✨ Feature, 민하 🎸

#416 Feat(client): 콘서트 및 페스티벌 상세 페이지 뷰 수정 및 api 연결
  apps/client/src/pages/performance/components/artist/artist-card.css.ts
  apps/client/src/pages/performance/components/artist/artist-card.tsx
  apps/client/src/pages/performance/components/artist/artist-grid.css.ts
  apps/client/src/pages/performance/components/artist/artist-section.css.ts
  apps/client/src/pages/performance/components/artist/artist-section.tsx
  apps/client/src/pages/performance/components/artist/artist-title.tsx
  apps/client/src/pages/performance/components/detail-info/detail-info.css.ts
  apps/client/src/pages/performance/components/detail-info/detail-info.tsx
  apps/client/src/pages/performance/components/hero/hero.css.ts
  apps/client/src/pages/performance/components/hero/hero.tsx
  apps/client/src/pages/performance/components/info/info.css.ts
  apps/client/src/pages/performance/components/info/info.tsx
  apps/client/src/pages/performance/components/location/location.css.ts
  apps/client/src/pages/performance/components/location/location.tsx
  apps/client/src/pages/performance/components/map-view/map-view.css.ts
  apps/client/src/pages/performance/components/map-view/map-view.tsx
  apps/client/src/pages/performance/components/performance-info/performance-info.css.ts
  apps/client/src/pages/performance/components/performance-info/performance-info.tsx
  apps/client/src/pages/performance/components/performance/performance-detail.css.ts
  apps/client/src/pages/performance/components/performance/performance-detail.tsx
  apps/client/src/pages/performance/components/poster/poster.css.ts
  apps/client/src/pages/performance/components/poster/poster.tsx
  apps/client/src/pages/performance/components/reservation/reservation.css.ts
  apps/client/src/pages/performance/components/reservation/reservation.tsx
  apps/client/src/pages/performance/components/summary/summary.tsx
  apps/client/src/pages/performance/constant/performance.ts
  apps/client/src/pages/performance/hooks/use-concert-detail.ts
  apps/client/src/pages/performance/hooks/use-festival-detail.ts
  apps/client/src/pages/performance/page/concert-detail.tsx
  apps/client/src/pages/performance/page/festival-detail.tsx
  apps/client/src/pages/performance/types/kakao.d.ts
  apps/client/src/pages/performance/utils/load-kakao-map.ts
  apps/client/src/shared/types/concert-response.ts
  apps/client/src/shared/types/festival-response.ts
  packages/design-system/src/components/avatar/avatar.tsx
  packages/design-system/src/icons/assets/ic_arrow_left_white_20.svg
  packages/design-system/src/icons/src/IcArrowLeftWhite20.tsx
  packages/design-system/src/icons/src/index.ts
  packages/design-system/src/styles/tokens/z-index.ts
Labels: ✨ Feature, 다현 🎧

#414 Feat(clinet): 내 공연 셋리스트 일부 & 전체 조회 api 연동
  apps/client/src/pages/my-history/hooks/use-my-history.ts
  apps/client/src/pages/my-history/page/overview/my-history-overview-page.tsx
  apps/client/src/pages/my-history/page/record/my-record.tsx
  apps/client/src/shared/apis/my-history/my-history-queries.ts
  apps/client/src/shared/apis/my-history/my-history.ts
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/constants/sort-label.ts
  apps/client/src/shared/types/my-history-response.ts
Labels: ✨ Feature, 지욱 🥁

#419 Feat(client): 홈 페이지 음악 재생 및 음악 새로고침 기능 추가
  apps/client/src/pages/home/components/suggest-music-section.css.ts
  apps/client/src/pages/home/components/suggest-music-section.tsx
  apps/client/src/pages/home/hooks/use-home-queries.ts
  apps/client/src/pages/home/page/home-page.tsx
  apps/client/src/shared/apis/home/home-queries.ts
  apps/client/src/shared/apis/home/home.ts
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/hooks/use-music-player.ts
  apps/client/src/shared/types/home-response.ts
  packages/design-system/src/components/music-item/music-item.css.ts
  packages/design-system/src/components/music-list/music-list.tsx
  packages/design-system/src/icons/assets/ic_load.svg
  packages/design-system/src/icons/src/IcLoad.tsx
  packages/design-system/src/icons/src/index.ts
Labels: ✨ Feature, 민하 🎸

#423 Feat(client): 내 공연 관람 기록 조회 api 연동
  apps/client/src/pages/my-history/hooks/use-my-history.ts
  apps/client/src/pages/my-history/page/record/my-record.tsx
  apps/client/src/shared/apis/my-history/my-history-queries.ts
  apps/client/src/shared/apis/my-history/my-history.ts
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/types/my-history-response.ts
Labels: ✨ Feature, 지욱 🥁

#420 Feat(client): 요청 공연 타입 분석 및 예정된 공연 목록 조회 API 연동
  apps/client/src/pages/search/components/search-result/performance/performance-section.tsx
  apps/client/src/pages/search/hooks/use-search-data.ts
  apps/client/src/pages/search/page/search-page.tsx
  apps/client/src/pages/search/page/search-result-page.tsx
  apps/client/src/shared/apis/search/search-queries.ts
  apps/client/src/shared/apis/search/search.ts
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/types/search-reponse.ts
Labels: ✨ Feature, 민하 🎸

#425 Fix(client): 음악 관련 데이터 구조 및 타입 변경
  apps/client/src/pages/home/components/suggest-music-section.tsx
  apps/client/src/pages/home/hooks/use-home-queries.ts
  apps/client/src/shared/apis/home/home-queries.ts
  apps/client/src/shared/apis/home/home.ts
  apps/client/src/shared/hooks/use-music-player.ts
  apps/client/src/shared/types/home-response.ts
  packages/design-system/src/components/music-list/music-list.tsx
Labels: 👾 Fix, 민하 🎸

#428 Feat(client): 셋리스트 공연추가 페이지 제작 및 조회 API 연동
  apps/client/src/pages/my-history/components/add-setlist/setlist-performance.css.ts
  apps/client/src/pages/my-history/components/add-setlist/setlist-performance.tsx
  apps/client/src/pages/my-history/components/preview/preview-section.tsx
  apps/client/src/pages/my-history/page/add-setlist/add-setlist-page.css.ts
  apps/client/src/pages/my-history/page/add-setlist/add-setlist-page.tsx
  apps/client/src/pages/my-history/page/hooks/use-performance-search.ts
  apps/client/src/pages/search/hooks/use-search-data.ts
  apps/client/src/pages/search/page/search-page.tsx
  apps/client/src/shared/apis/my-history/setlist-queries.ts
  apps/client/src/shared/apis/my-history/setlist.ts
  apps/client/src/shared/constants/path.ts
  apps/client/src/shared/hooks/use-related-search.ts
  apps/client/src/shared/router/lazy.ts
  apps/client/src/shared/router/router.tsx
  apps/client/src/shared/types/my-history-response.ts
  apps/client/src/shared/types/search-reponse.ts
  packages/design-system/src/components/search-suggestion-list/search-suggestion-list.tsx
Labels: ✨ Feature, 민하 🎸

#421 Feat(client): 프로필 편집 API 연동
  apps/client/src/pages/my/components/edit/edit-name-input.css.ts
  apps/client/src/pages/my/components/edit/edit-name-input.tsx
  apps/client/src/pages/my/components/edit/linked-account.css.ts
  apps/client/src/pages/my/components/edit/linked-account.tsx
  apps/client/src/pages/my/components/profile/user-info.css.ts
  apps/client/src/pages/my/components/profile/user-info.tsx
  apps/client/src/pages/my/page/edit/edit-profile.css.ts
  apps/client/src/pages/my/page/edit/edit-profile.tsx
  apps/client/src/pages/my/page/profile/my-profile.tsx
  apps/client/src/shared/apis/user/user.ts
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/constants/path.ts
  apps/client/src/shared/hooks/use-info-mutation.ts
  apps/client/src/shared/router/router.tsx
  apps/client/src/shared/types/user-response.ts
  apps/client/src/shared/utils/url-to-file.ts
  packages/design-system/src/icons/assets/btn_apple_active.svg
  packages/design-system/src/icons/assets/btn_apple_disabled.svg
  packages/design-system/src/icons/assets/btn_kakao_active.svg
  packages/design-system/src/icons/assets/btn_kakao_disabled.svg
  packages/design-system/src/icons/assets/ic_edit_16.svg
  packages/design-system/src/icons/assets/ic_toast_info_16.svg
  packages/design-system/src/icons/src/BtnAppleActive.tsx
  packages/design-system/src/icons/src/BtnAppleDisabled.tsx
  packages/design-system/src/icons/src/BtnKakaoActive.tsx
  packages/design-system/src/icons/src/BtnKakaoDisabled.tsx
  packages/design-system/src/icons/src/IcEdit16.tsx
  packages/design-system/src/icons/src/IcToastInfo16.tsx
  packages/design-system/src/icons/src/index.ts
Labels: ✨ Feature, 채은 🪕

#431 Feat(client): 인기&최근 검색어 기능 구현
  apps/client/src/pages/search/components/search-home/popular-search-section.tsx
  apps/client/src/pages/search/components/search-home/recent-search-section.tsx
  apps/client/src/pages/search/hooks/use-recent-search.ts
  apps/client/src/pages/search/hooks/use-search-data.ts
  apps/client/src/pages/search/hooks/use-search-logic.ts
  apps/client/src/pages/search/page/search-page.tsx
  apps/client/src/shared/apis/search/search-queries.ts
  apps/client/src/shared/apis/search/search.ts
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/types/search-reponse.ts
Labels: ✨ Feature, 민하 🎸

#435 Feat(client): 셋리스트 공연 추가 API 연동
  apps/client/src/pages/my-history/components/add-setlist/setlist-performance.tsx
  apps/client/src/pages/my-history/components/preview/preview-section.tsx
  apps/client/src/pages/my-history/hooks/use-add-performance-mutation.ts
  apps/client/src/pages/my-history/page/record/my-record.tsx
  apps/client/src/shared/apis/my-history/my-history.ts
  apps/client/src/shared/apis/my-history/setlist.ts
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/types/my-history-response.ts
Labels: ✨ Feature, 민하 🎸

#437 Fix(client): 셋리스트 응답 타입에서 setlistCount를 totalCount로 변경
  apps/client/src/pages/my-history/page/overview/my-history-overview-page.tsx
  apps/client/src/shared/types/my-history-response.ts
Labels: 👾 Fix, 지욱 🥁

#441 Fix(client): 토큰 재발급 로직 수정
  apps/client/src/shared/apis/config/interceptor.ts
Labels: 👾 Fix, 민하 🎸

#442 Feat(client): 애플로그인 연동
  apps/client/index.html
  apps/client/src/pages/home/page/home-page.tsx
  apps/client/src/pages/login/hooks/use-social-login-mutation.ts
  apps/client/src/pages/login/page/login.tsx
  apps/client/src/shared/apis/auth/auth.ts
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/types/login-response.ts
  apps/client/src/shared/utils/apple-login.ts
Labels: ✨ Feature, 민하 🎸

#446 Fix(client): 배포환경 엔드포인트 변경 문제 해결
  apps/client/src/shared/apis/auth/auth.ts
Labels: 👾 Fix, 민하 🎸

#443 Fix(design-system): 공연 캐러셀 제목이 레이아웃 벗어나는 오류 수정
  packages/design-system/src/components/performance-carousel/performance-carousel.css.ts
Labels: 👾 Fix, 한서 🎤

#448 Fix(client): fetch를 axios로 변경
  apps/client/src/shared/apis/auth/auth.ts
  apps/client/src/shared/constants/api.ts
Labels: 👾 Fix, 민하 🎸

#450 Feat(client): 타임테이블 오류 수정
  apps/client/src/pages/my-history/page/add-songs/add-songs-page.css.ts
  apps/client/src/pages/my-history/page/add-songs/add-songs-page.tsx
  apps/client/src/pages/time-table/hooks/use-festival-data.ts
  apps/client/src/pages/time-table/hooks/use-festival-select.ts
  apps/client/src/pages/time-table/page/time-table-page.tsx
Labels: 👾 Fix, 한서 🎤

#453 Feat(client): 타임테이블 오류 수정
  apps/client/src/pages/my/components/upcoming-performance/upcoming-performance-section.tsx
  apps/client/src/pages/time-table/hooks/use-festival-data.ts
  apps/client/src/pages/time-table/page/time-table-page.tsx
Labels: 👾 Fix, 한서 🎤

#455 Fix(client): 최근 검색결과 없을시 대체 텍스트 출력
  apps/client/src/pages/search/components/search-home/recent-festivals-section.tsx
  apps/client/src/pages/search/hooks/use-search-data.ts
  apps/client/src/pages/search/page/search-page.tsx
  apps/client/src/shared/apis/search/search-queries.ts
  apps/client/src/shared/hooks/use-navigate-to-detail.ts
Labels: 👾 Fix, 민하 🎸

#457 Refactor(client): 상세페이지 타이틀 줄바꿈 수정
  apps/client/src/pages/performance/components/hero/hero.css.ts
Labels: 🛠️ Refactor, 채은 🪕

#460 Feat(client): 마이 히스토리 페이지 컴포넌트간 비율 수정
  apps/client/src/pages/my-history/page/record/my-record.css.ts
  apps/client/src/pages/my-history/page/record/my-record.tsx
Labels: 👾 Fix, 지욱 🥁

#461 Refactor(client): 프로필 편집 페이지 수정
  apps/client/src/pages/my/components/profile/user-info.tsx
  apps/client/src/pages/my/page/edit/edit-profile.css.ts
  apps/client/src/pages/my/page/edit/edit-profile.tsx
  apps/client/src/shared/hooks/use-info-mutation.ts
  packages/design-system/src/components/toast/toast-container.css.ts
  packages/design-system/src/components/toast/toast.css.ts
Labels: 🛠️ Refactor, 채은 🪕

#462 Feat(client): 셋리스트 상세 뷰 구현 및 api 연결
  apps/client/src/pages/my-history/components/preview/preview-section.tsx
  apps/client/src/pages/my-history/components/setlist-detail/add-music-button.css.ts
  apps/client/src/pages/my-history/components/setlist-detail/add-music-button.tsx
  apps/client/src/pages/my-history/components/setlist-detail/setlist-detail-header.css.ts
  apps/client/src/pages/my-history/components/setlist-detail/setlist-detail-header.tsx
  apps/client/src/pages/my-history/components/setlist-detail/setlist-empty.css.ts
  apps/client/src/pages/my-history/components/setlist-detail/setlist-empty.tsx
  apps/client/src/pages/my-history/components/setlist-detail/setlist-tracks.css.ts
  apps/client/src/pages/my-history/components/setlist-detail/setlist-tracks.tsx
  apps/client/src/pages/my-history/hooks/use-delete-music-mutation.ts
  apps/client/src/pages/my-history/hooks/use-edit-cancel-on-leave.ts
  apps/client/src/pages/my-history/hooks/use-performance-search.ts
  apps/client/src/pages/my-history/hooks/use-setlist-detail.ts
  apps/client/src/pages/my-history/page/add-setlist/add-setlist-page.tsx
  apps/client/src/pages/my-history/page/setlist-detail/setlist-detail.tsx
  apps/client/src/pages/performance/page/concert-detail.tsx
  apps/client/src/pages/performance/page/festival-detail.tsx
  apps/client/src/shared/apis/my-history/setlist-queries.ts
  apps/client/src/shared/apis/my-history/setlist.ts
  apps/client/src/shared/components/hero/hero.css.ts
  apps/client/src/shared/components/hero/hero.tsx
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/constants/path.ts
  apps/client/src/shared/hooks/use-music-player.ts
  apps/client/src/shared/router/lazy.ts
  apps/client/src/shared/router/router.tsx
  apps/client/src/shared/types/my-history-response.ts
  packages/design-system/src/components/festival-card/festival-card.tsx
  packages/design-system/src/icons/assets/ic_add.svg
  packages/design-system/src/icons/src/IcAdd.tsx
  packages/design-system/src/icons/src/index.ts
Labels: ✨ Feature, 다현 🎧

#463 Fix(client): 온보딩 완료 페이지에서 로고 크기 조정 및 정렬 수정
  apps/client/src/pages/onboarding/components/onboarding-complete.css.ts
  apps/client/src/pages/onboarding/components/onboarding-complete.tsx
Labels: 👾 Fix, 지욱 🥁

#470 Fix(client): 온보딩 아티스트 선택 페이지 모바일 대응
  apps/client/src/pages/onboarding/components/artist-select.css.ts
Labels: 지욱 🥁, 🎨 Style

#465 Feat(client): 셋리스트 곡추가 페이지 퍼블리싱 & api 연동
  apps/client/src/pages/home/components/performance-carousel-section.css.ts
  apps/client/src/pages/my-history/page/add-songs/add-songs-page.css.ts
  apps/client/src/pages/my-history/page/add-songs/add-songs-page.tsx
  apps/client/src/pages/my-history/page/add-songs/confirm-add-section.css.ts
  apps/client/src/pages/my-history/page/add-songs/confirm-add-section.tsx
  apps/client/src/pages/my-history/page/hooks/use-music-search.ts
  apps/client/src/shared/apis/my-history/setlist-queries.ts
  apps/client/src/shared/apis/my-history/setlist.ts
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/constants/path.ts
  apps/client/src/shared/router/lazy.ts
  apps/client/src/shared/router/router.tsx
  apps/client/src/shared/types/my-history-response.ts
  packages/design-system/src/components/dialog/dialog.css.ts
Labels: ✨ Feature, 한서 🎤

#472 Fix(client): 온보딩 페이지 스타일 수정
  apps/client/src/pages/onboarding/components/artist-select.css.ts
Labels: 지욱 🥁, 🎨 Style

#474 Fix(client): require-login-section 스타일 수정하여 중앙 정렬 및 높이 조정
  apps/client/src/shared/pages/auth/require-login-section.css.ts
Labels: 👾 Fix, 지욱 🥁

#476 Refactor(design-system): 아티스트 더보기 UX개선
  apps/client/src/pages/performance/components/expanded/expanded-section.css.ts
  apps/client/src/pages/performance/components/expanded/expanded-section.tsx
Labels: 🛠️ Refactor, 지욱 🥁

#478 Feat(client): setlist 곡추가 api 연결
  apps/client/src/pages/my-history/components/setlist-detail/setlist-empty.tsx
  apps/client/src/pages/my-history/hooks/use-add-songs-mutation.ts
  apps/client/src/pages/my-history/hooks/use-music-search.ts
  apps/client/src/pages/my-history/page/add-songs/add-songs-page.tsx
  apps/client/src/pages/my-history/page/add-songs/confirm-add-section.tsx
  apps/client/src/pages/my-history/page/setlist-detail/setlist-detail.tsx
  apps/client/src/shared/apis/my-history/setlist.ts
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/constants/path.ts
  apps/client/src/shared/types/my-history-response.ts
Labels: ✨ Feature, 한서 🎤

#483 Feat(design-system): 스켈레톤 컴포넌트 구현
  packages/design-system/src/components/search-suggestion-list/search-suggestion-list.stories.tsx
  packages/design-system/src/components/skeleton/skeleton.css.ts
  packages/design-system/src/components/skeleton/skeleton.stories.tsx
  packages/design-system/src/components/skeleton/skeleton.tsx
Labels: ✨ Feature, 지욱 🥁

#484 Fix(client): 타임테이블 보드 레이아웃 수정
  apps/client/src/pages/time-table/components/time-table-board/time-cell.css.ts
  apps/client/src/pages/time-table/components/time-table-board/time-table-item.css.ts
  apps/client/src/pages/time-table/components/time-table-board/time-table-item.tsx
  apps/client/src/pages/time-table/utils/index.ts
Labels: 👾 Fix, 민하 🎸

#481 Fix(client): 홈/페스티벌 및 공연추가 페이지 스타일 수정
  apps/client/src/pages/home/components/performance-carousel-section.css.ts
  apps/client/src/pages/my-history/components/add-setlist/setlist-performance.css.ts
  apps/client/src/pages/my-history/components/add-setlist/setlist-performance.tsx
  apps/client/src/pages/time-table/page/add-festival/add-festival.css.ts
  apps/client/src/pages/time-table/page/add-festival/add-festival.tsx
  packages/design-system/src/components/festival-card/festival-card.css.ts
  packages/design-system/src/components/performance-carousel/performance-carousel.css.ts
Labels: 👾 Fix, 한서 🎤

#468 Feat(client): 셋리스트 드래그앤드롭 구현 & api 연동
  apps/client/package.json
  apps/client/src/pages/my-history/components/setlist-detail/setlist-detail-header.tsx
  apps/client/src/pages/my-history/components/setlist-detail/setlist-tracks.tsx
  apps/client/src/pages/my-history/hooks/use-setlist-detail.ts
  apps/client/src/pages/my-history/page/add-songs/add-songs-page.tsx
  apps/client/src/pages/my-history/page/add-songs/confirm-add-section.tsx
  apps/client/src/pages/my-history/page/setlist-detail/setlist-detail.tsx
  apps/client/src/shared/apis/my-history/setlist.ts
  apps/client/src/shared/components/hero/hero.css.ts
  apps/client/src/shared/constants/api.ts
  packages/design-system/package.json
  packages/design-system/src/components/music-item/music-item.css.ts
  packages/design-system/src/components/music-item/music-item.tsx
  packages/design-system/src/components/music-list/music-list.tsx
  pnpm-lock.yaml
Labels: ✨ Feature, 채은 🪕

#488 Fix(client): 곡 추가 페이지 음악재생 안되는 문제 해결
  apps/client/src/pages/my-history/components/setlist-detail/setlist-tracks.tsx
  apps/client/src/pages/my-history/page/add-songs/add-songs-page.css.ts
  apps/client/src/pages/my-history/page/add-songs/add-songs-page.tsx
  packages/design-system/src/components/music-item/music-item.css.ts
  packages/design-system/src/components/music-item/music-item.tsx
  packages/design-system/src/components/music-list/music-list.tsx
Labels: 👾 Fix, 민하 🎸

#491 Fix(client): empty-festival 컴포넌트 뷰 수정
  apps/client/src/pages/time-table/components/empty/empty-festival-section.css.ts
Labels: 👾 Fix, 지욱 🥁

#493 Fix(design-system): 음악 아이템 제목의 최대 너비 및 너비 설정 추가
  packages/design-system/src/components/music-item/music-item.css.ts
Labels: 👾 Fix, 지욱 🥁

#495 Fix(client): 드래그 훅 추가
  apps/client/src/pages/my-history/components/setlist-detail/setlist-tracks.tsx
  apps/client/src/pages/my-history/hooks/use-prevent-scroll.ts
  packages/design-system/src/components/music-item/music-item.css.ts
Labels: 채은 🪕
