Repository team-confeti/confeti-client, pull requests merged in 2025-01, with the labels that each got.

#8 Chore: root 환경 eslint 속성 추가
  .eslintrc.cjs
Labels: ⚙️ Setting, 🥁 지욱

#12 Chore: discord 알림 .yml 파일 생성
  .github/workflows/discord-notify.yml
Labels: ⚙️ Setting, 🥁 지욱

#21 Init: 라우터 초기세팅
  apps/client/package.json
  apps/client/src/App.tsx
  apps/client/src/pages/home/page/.gitkeep
  apps/client/src/pages/home/page/home.tsx
  apps/client/src/shared/constants/.gitkeep
  apps/client/src/shared/constants/path.ts
  apps/client/src/shared/router/.gitkeep
  apps/client/src/shared/router/global-layout.tsx
  apps/client/src/shared/router/lazy.ts
  apps/client/src/shared/router/router.tsx
  pnpm-lock.yaml
Labels: ✨ Feature, ⚙️ Setting, 🥁 지욱

#26 Init: ci cd 워크플로우 세팅
  .github/workflows/build-test.yml
  .github/workflows/discord-notify.yml
  .github/workflows/sync.yml
Labels: ⚙️ Setting, 🌎 Deploy, 🎹 다현

#28 Refactor: sync.yml 파일 수정
  .github/workflows/sync.yml
Labels: 🛠️ Refactor, 🥁 지욱

#24 Init: svgr 세팅
  .eslintrc.cjs
  packages/design-system/package.json
  packages/design-system/src/icons/.gitkeep
  packages/design-system/src/icons/assets/symbol logo.svg
  packages/design-system/src/icons/src/index.ts
  packages/design-system/src/icons/src/svg/SymbolLogo.tsx
  pnpm-lock.yaml
Labels: ⚙️ Setting, 🎤 한서, 🪕 채은

#32 Delete: 필요없는 파일, rules 삭제
  .eslintrc.cjs
  .husky/.gitkeep
Labels: 🛠️ Refactor, 🥁 지욱

#31 Init: .nvmrc 세팅
  .nvmrc
Labels: ⚙️ Setting, 🎸 민하

#35 Init: turbo/gen 컴포넌트 generator 세팅
  .prettierignore
  packages/design-system/.storybook/main.ts
  packages/design-system/.storybook/manager-head.html
  packages/design-system/.storybook/public/favicon_red.svg
  packages/design-system/package.json
  packages/design-system/src/components/button/Button.stories.ts
  packages/design-system/src/components/button/button.tsx
  packages/design-system/src/stories/Introduction.mdx
  packages/design-system/turbo/generators/config.ts
  packages/design-system/turbo/generators/templates/component.hbs
  packages/design-system/turbo/generators/templates/css.hbs
  packages/design-system/turbo/generators/templates/stories.hbs
  pnpm-lock.yaml
Labels: ✨ Feature, ⚙️ Setting, 🎸 민하

#23 Init: 디자인 토큰 초기세팅
  apps/client/src/App.tsx
  packages/design-system/src/styles/font/font.css
  packages/design-system/src/styles/global.css.ts
  packages/design-system/src/styles/index.ts
  packages/design-system/src/styles/theme.css.ts
  packages/design-system/src/styles/tokens/.gitkeep
  packages/design-system/src/styles/tokens/color.css.ts
  packages/design-system/src/styles/tokens/font-styles.css.ts
  packages/design-system/src/styles/tokens/typography.css.ts
Labels: ⚙️ Setting, 🎹 다현

#38 Refactor: global style 모바일 뷰 수정
  packages/design-system/src/styles/global.css.ts
Labels: 🛠️ Refactor, 🎹 다현

#40 Refactor: CI 빌드 속도 개선 및 설정 변경
  .github/workflows/build-test.yml
  .github/workflows/build.yml
  .github/workflows/chromatic.yml
  .vscode/settings.json
  apps/client/package.json
  config/eslint/library.js
  config/eslint/package.json
  config/eslint/react-internal.js
  package.json
  packages/design-system/src/components/button/button.css.ts
  pnpm-lock.yaml
Labels: ⚙️ Setting, 🌎 Deploy, 🎸 민하

#42 Refactor: 불필요한 import문 자동생성되지 않도록 svgr 옵션 추가
  packages/design-system/package.json
  packages/design-system/src/icons/src/SymbolLogo.tsx
Labels: 🛠️ Refactor, 🎤 한서

#51 Docs: README 작성
  README.md
Labels: 📑 Docs

#53 Feat: 타이포 토큰 및 폰트 스타일 업데이트
  packages/design-system/src/styles/tokens/font-styles.css.ts
  packages/design-system/src/styles/tokens/typography.css.ts
Labels: ✨ Feature, 다현 🎧

#50 Feat: svg 아이콘 변환
  packages/design-system/src/icons/assets/btn_account_black_24.svg
  packages/design-system/src/icons/assets/btn_arrow_left_20.svg
  packages/design-system/src/icons/assets/btn_arrow_left_24.svg
  packages/design-system/src/icons/assets/btn_close.svg
  packages/design-system/src/icons/assets/btn_floating.svg
  packages/design-system/src/icons/assets/btn_heart_default_24.svg
  packages/design-system/src/icons/assets/btn_heart_filled_24.svg
  packages/design-system/src/icons/assets/btn_search_black_24.svg
  packages/design-system/src/icons/assets/ic_arrow_gray_16.svg
  packages/design-system/src/icons/assets/ic_arrow_white_12.svg
  packages/design-system/src/icons/assets/ic_place_gray_14.svg
  packages/design-system/src/icons/assets/ic_sic_gray_18.svg
  packages/design-system/src/icons/assets/ic_time_gray_14.svg
  packages/design-system/src/icons/assets/logo_footer.svg
  packages/design-system/src/icons/assets/logo_main.svg
  packages/design-system/src/icons/assets/logo_symbol.svg
  packages/design-system/src/icons/assets/symbolLogo.svg
  packages/design-system/src/icons/src/BtnAccountBlack24.tsx
  packages/design-system/src/icons/src/BtnArrowLeft20.tsx
  packages/design-system/src/icons/src/BtnArrowLeft24.tsx
  packages/design-system/src/icons/src/BtnClose.tsx
  packages/design-system/src/icons/src/BtnFloating.tsx
  packages/design-system/src/icons/src/BtnHeartDefault24.tsx
  packages/design-system/src/icons/src/BtnHeartFilled24.tsx
  packages/design-system/src/icons/src/BtnSearchBlack24.tsx
  packages/design-system/src/icons/src/IcArrowGray16.tsx
  packages/design-system/src/icons/src/IcArrowWhite12.tsx
  packages/design-system/src/icons/src/IcPlaceGray14.tsx
  packages/design-system/src/icons/src/IcSicGray18.tsx
  packages/design-system/src/icons/src/IcTimeGray14.tsx
  packages/design-system/src/icons/src/LogoFooter.tsx
  packages/design-system/src/icons/src/LogoMain.tsx
  packages/design-system/src/icons/src/LogoSymbol.tsx
  packages/design-system/src/icons/src/SymbolLogo.tsx
  packages/design-system/src/icons/src/index.ts
Labels: ✨ Feature, 채은 🪕

#54 Feat: svg 아이콘 추가 변환
  packages/design-system/src/icons/assets/btn_account_gray_24.svg
  packages/design-system/src/icons/assets/btn_search_g900_24.svg
  packages/design-system/src/icons/assets/ic_festival_gray.svg
  packages/design-system/src/icons/assets/ic_indicator_active.svg
  packages/design-system/src/icons/assets/ic_indicator_default.svg
  packages/design-system/src/icons/assets/ic_link.svg
  packages/design-system/src/icons/assets/ic_select.svg
  packages/design-system/src/icons/assets/ic_toast_info_24.svg
  packages/design-system/src/icons/assets/logo_main.svg
  packages/design-system/src/icons/src/BtnAccountGray24.tsx
  packages/design-system/src/icons/src/BtnSearchG90024.tsx
  packages/design-system/src/icons/src/IcFestivalGray.tsx
  packages/design-system/src/icons/src/IcIndicatorActive.tsx
  packages/design-system/src/icons/src/IcIndicatorDefault.tsx
  packages/design-system/src/icons/src/IcLink.tsx
  packages/design-system/src/icons/src/IcSelect.tsx
  packages/design-system/src/icons/src/IcToastInfo24.tsx
  packages/design-system/src/icons/src/LogoMain.tsx
  packages/design-system/src/icons/src/index.ts
Labels: ✨ Feature, 채은 🪕

#56 Feat: Footer 컴포넌트 제작
  apps/client/src/pages/home/page/home.tsx
  packages/design-system/.storybook/preview.tsx
  packages/design-system/src/components/footer/footer.css.ts
  packages/design-system/src/components/footer/footer.stories.tsx
  packages/design-system/src/components/footer/footer.tsx
  packages/design-system/src/components/index.ts
  packages/design-system/src/styles/reset.css.ts
  packages/design-system/src/styles/theme.css.ts
  packages/design-system/src/styles/tokens/color.ts
  packages/design-system/src/styles/tokens/font-styles.ts
  packages/design-system/src/styles/tokens/typography.ts
Labels: ✨ Feature, 민하 🎸

#55 Feat(design-system): 버튼 컴포넌트 설계구현
  apps/client/index.html
  apps/client/src/pages/home/page/home.tsx
  packages/design-system/.storybook/preview-head.html
  packages/design-system/src/components/button/Button.stories.ts
  packages/design-system/src/components/button/button.css.ts
  packages/design-system/src/components/button/button.stories.tsx
  packages/design-system/src/components/button/button.tsx
  packages/design-system/src/components/index.ts
Labels: ✨ Feature, 지욱 🥁

#57 Feat(design-system): Header 컴포넌트 구현
  apps/client/src/shared/router/global-layout.tsx
  packages/design-system/package.json
  packages/design-system/src/components/header/header.css.ts
  packages/design-system/src/components/header/header.stories.tsx
  packages/design-system/src/components/header/header.tsx
  packages/design-system/src/components/index.ts
  packages/design-system/src/styles/theme.css.ts
  packages/design-system/src/styles/tokens/border.ts
  pnpm-lock.yaml
Labels: ✨ Feature, 다현 🎧

#60 Feat(design-system): Toast 컴포넌트 구현
  apps/client/src/App.tsx
  packages/design-system/src/components/index.ts
  packages/design-system/src/components/toast/hooks/useToastContainer.tsx
  packages/design-system/src/components/toast/toast-container.css.ts
  packages/design-system/src/components/toast/toast-container.tsx
  packages/design-system/src/components/toast/toast.css.ts
  packages/design-system/src/components/toast/toast.stories.tsx
  packages/design-system/src/components/toast/toast.tsx
  packages/design-system/src/components/toast/types/type.ts
  packages/design-system/src/components/toast/utils/eventManager.ts
  packages/design-system/src/components/toast/utils/toast.ts
  packages/design-system/src/styles/theme.css.ts
  packages/design-system/src/styles/tokens/display.ts
  packages/design-system/src/styles/tokens/z-index.ts
  packages/design-system/turbo/generators/templates/component.hbs
  packages/design-system/turbo/generators/templates/stories.hbs
Labels: ✨ Feature, 민하 🎸

#67 Feat(design-system) Floating 버튼 구현
  .eslintrc.cjs
  packages/design-system/src/components/button/button.stories.tsx
  packages/design-system/src/components/floating-button/floating-button.css.ts
  packages/design-system/src/components/floating-button/floating-button.stories.tsx
  packages/design-system/src/components/floating-button/floating-button.tsx
  packages/design-system/src/components/index.ts
  packages/design-system/src/components/toast/hooks/useToastContainer.tsx
  packages/design-system/src/icons/assets/btn_floating.svg
  packages/design-system/src/icons/assets/ic_arrow_up_black_30.svg
  packages/design-system/src/icons/src/BtnFloating.tsx
  packages/design-system/src/icons/src/IcArrowUpBlack30.tsx
  packages/design-system/src/icons/src/index.ts
  packages/design-system/src/styles/global.css.ts
  packages/design-system/src/styles/theme.css.ts
  packages/design-system/src/styles/tokens/box-shadow.ts
  packages/design-system/src/styles/tokens/z-index.ts
Labels: ✨ Feature, 지욱 🥁

#61 Feat(design-system): Navigation 컴포넌트 구현
  apps/client/src/pages/home/constants/.gitkeep
  apps/client/src/pages/home/constants/menu.ts
  apps/client/src/pages/home/page/home.tsx
  packages/design-system/.storybook/preview.tsx
  packages/design-system/src/components/footer/footer.stories.tsx
  packages/design-system/src/components/index.ts
  packages/design-system/src/components/navigation/navigation.css.ts
  packages/design-system/src/components/navigation/navigation.stories.tsx
  packages/design-system/src/components/navigation/navigation.tsx
  packages/design-system/src/stories/Introduction.mdx
  packages/design-system/src/styles/tokens/display.ts
Labels: ✨ Feature, 한서 🎤

#66 Feat(design-system): SearchBar 컴포넌트 구현
  apps/client/src/shared/components/.gitkeep
  packages/design-system/src/components/header/header.css.ts
  packages/design-system/src/components/search-bar/SearchBar.stories.ts
  packages/design-system/src/components/search-bar/search-bar.css.ts
  packages/design-system/src/components/search-bar/search-bar.tsx
  packages/design-system/src/icons/src/BtnClose.tsx
  packages/design-system/src/styles/tokens/border.ts
Labels: ✨ Feature, 채은 🪕

#72 Feat(design-system): spacing 컴포넌트 추가
  packages/design-system/src/components/index.ts
  packages/design-system/src/components/spacing/spacing.css.ts
  packages/design-system/src/components/spacing/spacing.stories.tsx
  packages/design-system/src/components/spacing/spacing.tsx
Labels: ✨ Feature, 민하 🎸

#70 Feat(client): 마이페이지 및 UserInfo 컴포넌트 추가
  apps/client/src/pages/my/components/.gitkeep
  apps/client/src/pages/my/components/logout-button.css.ts
  apps/client/src/pages/my/components/logout-button.tsx
  apps/client/src/pages/my/components/user-info.css.ts
  apps/client/src/pages/my/components/user-info.tsx
  apps/client/src/pages/my/page/.gitkeep
  apps/client/src/pages/my/page/my.tsx
  apps/client/src/shared/constants/path.ts
  apps/client/src/shared/mocks/user-data.ts
  apps/client/src/shared/router/lazy.ts
  apps/client/src/shared/router/router.tsx
  packages/design-system/src/styles/tokens/border.ts
  packages/design-system/src/styles/tokens/color.ts
Labels: ✨ Feature, 민하 🎸

#74 Feat(design-system): Artist Card 컴포넌트 구현
  packages/design-system/src/components/artist-card/artist-card.css.ts
  packages/design-system/src/components/artist-card/artist-card.stories.tsx
  packages/design-system/src/components/artist-card/artist-card.tsx
  packages/design-system/src/styles/reset.css.ts
  packages/design-system/src/styles/tokens/display.ts
Labels: ✨ Feature, 채은 🪕

#87 Feat(client): 마이페이지 퍼블리싱
  apps/client/src/pages/my/components/artist-section.css.ts
  apps/client/src/pages/my/components/artist-section.tsx
  apps/client/src/pages/my/components/box.css.ts
  apps/client/src/pages/my/components/box.tsx
  apps/client/src/pages/my/components/confeti-section.css.ts
  apps/client/src/pages/my/components/conteti-section.tsx
  apps/client/src/pages/my/components/no-artist-section.css.ts
  apps/client/src/pages/my/components/no-artist-section.tsx
  apps/client/src/pages/my/components/no-confeti-section.css.ts
  apps/client/src/pages/my/components/no-confeti-section.tsx
  apps/client/src/pages/my/components/user-info.css.ts
  apps/client/src/pages/my/page/my.tsx
  apps/client/src/shared/mocks/artists-data.ts
  packages/design-system/package.json
  packages/design-system/src/components/artist-card/artist-card.css.ts
  packages/design-system/src/components/artist-card/artist-card.stories.tsx
  packages/design-system/src/components/artist-card/artist-card.tsx
  packages/design-system/src/components/footer/footer.css.ts
  packages/design-system/src/components/index.ts
  packages/design-system/src/styles/global.css.ts
  packages/design-system/src/styles/reset.css.ts
Labels: ✨ Feature, 민하 🎸

#80 Feat(design-system): 홈 배너 상단 캐러셀 구현
  apps/client/src/pages/home/page/home.css.ts
  apps/client/src/pages/home/page/home.tsx
  apps/client/src/shared/mocks/top-carousel-mock.ts
  packages/design-system/package.json
  packages/design-system/src/components/index.ts
  packages/design-system/src/components/top-carousel/dots.css.ts
  packages/design-system/src/components/top-carousel/slick.css.ts
  packages/design-system/src/components/top-carousel/top-carousel.css.ts
  packages/design-system/src/components/top-carousel/top-carousel.stories.tsx
  packages/design-system/src/components/top-carousel/top-carousel.tsx
  packages/design-system/src/styles/tokens/color.ts
  packages/design-system/tsconfig.json
  pnpm-lock.yaml
Labels: ✨ Feature, 한서 🎤

#90 Feat(client): 타임테이블 플로팅 컴포넌트 제작
  apps/client/package.json
  apps/client/src/pages/home/page/home.tsx
  apps/client/src/pages/time-table/components/.gitkeep
  apps/client/src/pages/time-table/components/edit-floating-button.css.ts
  apps/client/src/pages/time-table/components/edit-floating-button.tsx
  apps/client/src/pages/time-table/constants/edit-floating-text.ts
  packages/design-system/src/components/navigation/navigation.css.ts
  packages/design-system/src/icons/assets/ic_float_delete_24.svg
  packages/design-system/src/icons/assets/ic_float_edit_24.svg
  packages/design-system/src/icons/assets/ic_float_edit_lime_24.svg
  packages/design-system/src/icons/assets/ic_timetable_float_close.svg
  packages/design-system/src/icons/assets/ic_timetable_float_finish.svg
  packages/design-system/src/icons/src/IcFloatDelete24.tsx
  packages/design-system/src/icons/src/IcFloatEdit24.tsx
  packages/design-system/src/icons/src/IcFloatEditLime24.tsx
  packages/design-system/src/icons/src/IcTimetableFloatClose.tsx
  packages/design-system/src/icons/src/IcTimetableFloatFinish.tsx
  packages/design-system/src/icons/src/index.ts
  packages/design-system/src/styles/tokens/z-index.ts
  pnpm-lock.yaml
Labels: ✨ Feature, 민하 🎸

#89 Feat(client): 서치 페이지 퍼블리싱
  apps/client/src/pages/search/components/.gitkeep
  apps/client/src/pages/search/components/artist-info.css.ts
  apps/client/src/pages/search/components/artist-info.tsx
  apps/client/src/pages/search/components/artist-not-found.css.ts
  apps/client/src/pages/search/components/artist-not-found.tsx
  apps/client/src/pages/search/components/artist-section.css.ts
  apps/client/src/pages/search/components/artist-section.tsx
  apps/client/src/pages/search/components/notice-section.css.ts
  apps/client/src/pages/search/components/notice-section.tsx
  apps/client/src/pages/search/components/performance-count-section.css.ts
  apps/client/src/pages/search/components/performance-count-section.tsx
  apps/client/src/pages/search/components/performance-info.css.ts
  apps/client/src/pages/search/components/performance-info.tsx
  apps/client/src/pages/search/components/performance-section.css.ts
  apps/client/src/pages/search/components/performance-section.tsx
  apps/client/src/pages/search/components/title.css.ts
  apps/client/src/pages/search/components/title.tsx
  apps/client/src/pages/search/constants/notice-message.ts
  apps/client/src/pages/search/hooks/.gitkeep
  apps/client/src/pages/search/hooks/use-search.ts
  apps/client/src/pages/search/hooks/use-sorted-performances.ts
  apps/client/src/pages/search/mocks/searched-artist-data.ts
  apps/client/src/pages/search/mocks/searched-performance-data.ts
  apps/client/src/pages/search/page/.gitkeep
  apps/client/src/pages/search/page/search.css.ts
  apps/client/src/pages/search/page/search.tsx
  apps/client/src/shared/constants/path.ts
  apps/client/src/shared/router/lazy.ts
  apps/client/src/shared/router/router.tsx
  packages/design-system/src/components/header/header.css.ts
  packages/design-system/src/components/header/header.tsx
  packages/design-system/src/components/index.ts
  packages/design-system/src/components/search-bar/search-bar.css.ts
  packages/design-system/src/components/search-bar/search-bar.tsx
  packages/design-system/src/icons/assets/ic_exclamation_circle_outlined_32.svg
  packages/design-system/src/icons/src/IcExclamationCircleOutlined32.tsx
  packages/design-system/src/icons/src/index.ts
  packages/design-system/src/styles/tokens/border.ts
  packages/design-system/src/styles/tokens/display.ts
Labels: ✨ Feature, 다현 🎧

#100 Refactor(design-system): 스토리북 수정
  packages/design-system/src/components/artist-card/artist-card.stories.tsx
  packages/design-system/src/components/button/button.stories.tsx
  packages/design-system/src/components/button/button.tsx
  packages/design-system/src/components/festival-card/festival-card.stories.tsx
  packages/design-system/src/components/toast/toast.css.ts
  packages/design-system/src/components/toast/toast.stories.tsx
Labels: 🛠️ Refactor, 민하 🎸

#88 Feat(client): 아티스트 더보기 페이지 퍼블리싱
  apps/client/src/pages/my/page/artist-detail.css.ts
  apps/client/src/pages/my/page/artist-detail.tsx
  apps/client/src/shared/constants/path.ts
  apps/client/src/shared/mocks/artist-data.ts
  apps/client/src/shared/router/lazy.ts
  apps/client/src/shared/router/router.tsx
  packages/design-system/src/components/artist-card/artist-card.css.ts
  packages/design-system/src/components/artist-card/artist-card.tsx
  packages/design-system/src/components/index.ts
Labels: ✨ Feature, 채은 🪕

#101 Feat(client): 공연 상세정보 페이지 공연 섹션 퍼블리싱
  apps/client/src/pages/confeti/components/info.css.ts
  apps/client/src/pages/confeti/components/info.tsx
  apps/client/src/pages/confeti/components/performance-detail.css.ts
  apps/client/src/pages/confeti/components/performance-detail.tsx
  apps/client/src/pages/confeti/components/poster.css.ts
  apps/client/src/pages/confeti/components/poster.tsx
  apps/client/src/pages/confeti/components/summary.css.ts
  apps/client/src/pages/confeti/components/summary.tsx
  apps/client/src/pages/confeti/constant/confeti.ts
  apps/client/src/pages/confeti/hooks/.gitkeep
  apps/client/src/pages/confeti/page/concert-detail.css.ts
  apps/client/src/pages/confeti/page/concert-detail.tsx
  apps/client/src/pages/confeti/page/festival-detail.css.ts
  apps/client/src/pages/confeti/page/festival-detail.tsx
  apps/client/src/pages/confeti/types/.gitkeep
  apps/client/src/shared/constants/path.ts
  apps/client/src/shared/router/lazy.ts
  apps/client/src/shared/router/router.tsx
  packages/design-system/src/components/button/button.css.ts
  packages/design-system/src/components/index.ts
  packages/design-system/src/styles/tokens/z-index.ts
Labels: ✨ Feature, 채은 🪕

#103 Feat(client): 마이페이지 추가
  apps/client/src/pages/my/components/artist/artist-section.css.ts
  apps/client/src/pages/my/components/artist/artist-section.tsx
  apps/client/src/pages/my/components/artist/no-artist-section.css.ts
  apps/client/src/pages/my/components/artist/no-artist-section.tsx
  apps/client/src/pages/my/components/auth/require_login_section.css.ts
  apps/client/src/pages/my/components/auth/require_login_section.tsx
  apps/client/src/pages/my/components/confeti/confeti-section.css.ts
  apps/client/src/pages/my/components/confeti/conteti-section.tsx
  apps/client/src/pages/my/components/confeti/no-confeti-section.css.ts
  apps/client/src/pages/my/components/confeti/no-confeti-section.tsx
  apps/client/src/pages/my/components/profile/box.css.ts
  apps/client/src/pages/my/components/profile/box.tsx
  apps/client/src/pages/my/components/profile/logout-button.css.ts
  apps/client/src/pages/my/components/profile/logout-button.tsx
  apps/client/src/pages/my/components/profile/user-info.css.ts
  apps/client/src/pages/my/components/profile/user-info.tsx
  apps/client/src/pages/my/page/artist/artist-detail.css.ts
  apps/client/src/pages/my/page/artist/artist-detail.tsx
  apps/client/src/pages/my/page/auth/require_login.tsx
  apps/client/src/pages/my/page/confeti/confeti-detail.css.ts
  apps/client/src/pages/my/page/confeti/confeti-detail.tsx
  apps/client/src/pages/my/page/my-page.tsx
  apps/client/src/pages/my/page/profile/my-profile.tsx
  apps/client/src/shared/constants/path.ts
  apps/client/src/shared/router/lazy.ts
  apps/client/src/shared/router/router.tsx
Labels: ✨ Feature, 민하 🎸

#104 Fix(client): 글로벌 스타일 수정
  apps/client/src/App.tsx
  apps/client/src/pages/home/page/home.css.ts
  apps/client/src/pages/home/page/home.tsx
  packages/design-system/src/components/top-carousel/top-carousel.tsx
  packages/design-system/src/styles/global.css.ts
Labels: 👾 Fix, 민하 🎸

#108 Feat(client): vite 서버 호스트 설정 추가
  apps/client/vite.config.ts
Labels: ⚙️ Setting, 민하 🎸

#111 Feat(client): 홈 페이지 퍼블리싱
  apps/client/src/App.tsx
  apps/client/src/pages/home/page/home.css.ts
  apps/client/src/pages/home/page/home.tsx
  apps/client/src/pages/my/components/auth/require_login_section.tsx
  apps/client/src/pages/my/components/profile/user-info.tsx
  apps/client/src/pages/search/components/artist-not-found.css.ts
  apps/client/src/shared/constants/user-constants.ts
  apps/client/src/shared/mocks/banner-data.ts
  apps/client/src/shared/mocks/top-carousel-mock.ts
  apps/client/src/shared/router/protected-route.tsx
  apps/client/src/shared/router/router.tsx
  packages/design-system/src/components/index.ts
  packages/design-system/src/components/performance-carousel/dots.css.ts
  packages/design-system/src/components/performance-carousel/performance-carousel.css.ts
  packages/design-system/src/components/performance-carousel/performance-carousel.stories.tsx
  packages/design-system/src/components/performance-carousel/performance-carousel.tsx
  packages/design-system/src/components/performance-carousel/slick.css.ts
  packages/design-system/src/components/ticketing-carousel/hooks/use-carousel-data.ts
  packages/design-system/src/components/ticketing-carousel/hooks/use-carousel-slide.ts
  packages/design-system/src/components/ticketing-carousel/hooks/use-control-time.ts
  packages/design-system/src/components/ticketing-carousel/hooks/use-data-format.ts
  packages/design-system/src/components/ticketing-carousel/info-button/info-button.css.ts
  packages/design-system/src/components/ticketing-carousel/info-button/info-button.stories.tsx
  packages/design-system/src/components/ticketing-carousel/info-button/info-button.tsx
  packages/design-system/src/components/ticketing-carousel/mocks/bottom-banner-data.ts
  packages/design-system/src/components/ticketing-carousel/progress-bar/progress-bar.css.ts
  packages/design-system/src/components/ticketing-carousel/progress-bar/progress-bar.stories.tsx
  packages/design-system/src/components/ticketing-carousel/progress-bar/progress-bar.tsx
  packages/design-system/src/components/ticketing-carousel/ticketingCarousel-carousel.css.ts
  packages/design-system/src/components/ticketing-carousel/ticketingCarousel-carousel.stories.tsx
  packages/design-system/src/components/ticketing-carousel/ticketingCarousel-carousel.tsx
  packages/design-system/src/styles/global.css.ts
  packages/design-system/src/styles/tokens/box-shadow.ts
  packages/design-system/src/styles/tokens/color.ts
  packages/design-system/src/styles/tokens/font-styles.ts
  packages/design-system/src/styles/tokens/typography.ts
Labels: ✨ Feature, 민하 🎸

#123 Feat(client): 공연 상세보기 퍼블리싱
  apps/client/src/pages/confeti/components/summary.tsx
  apps/client/src/pages/confeti/mocks/confeti-detail.ts
  apps/client/src/pages/confeti/page/concert-detail.tsx
  apps/client/src/pages/confeti/page/festival-detail.tsx
Labels: ✨ Feature, 다현 🎧

#110 Feat(client): 페스티벌 추가 페이지 퍼블리싱
  apps/client/src/pages/time-table/hooks/use-festival-selection.ts
  apps/client/src/pages/time-table/page/.gitkeep
  apps/client/src/pages/time-table/page/add-festival.css.ts
  apps/client/src/pages/time-table/page/add-festival.tsx
  apps/client/src/shared/constants/path.ts
  apps/client/src/shared/mocks/performance-data.ts
  apps/client/src/shared/router/lazy.ts
  apps/client/src/shared/router/router.tsx
  packages/design-system/src/components/button/button.css.ts
  packages/design-system/src/components/festival-card/festival-card.tsx
  packages/design-system/src/components/footer/footer.tsx
  packages/design-system/src/components/toast/toast.css.ts
Labels: ✨ Feature, 채은 🪕

#120 Fix(design-system): 페스티벌 카드 모바일 화면 깨짐 해결
  apps/client/src/shared/mocks/performance-data.ts
  packages/design-system/src/components/festival-card/festival-card.css.ts
Labels: 👾 Fix, 민하 🎸

#132 Fix: (QA/1) 스타일 깨지게 적용되는 부분 수정
  packages/design-system/src/components/navigation/navigation.tsx
Labels: 👾 Fix, 한서 🎤

#131 Feat(client): 페스티벌 추가 안내 페이지 구현
  apps/client/src/pages/time-table/components/empty/empty-festival-section.css.ts
  apps/client/src/pages/time-table/components/empty/empty-festival-section.tsx
  apps/client/src/pages/time-table/page/empty/empty-festival.tsx
  apps/client/src/pages/time-table/page/time-table-layout.tsx
  apps/client/src/shared/constants/path.ts
  apps/client/src/shared/router/lazy.ts
  apps/client/src/shared/router/router.tsx
Labels: ✨ Feature, 다현 🎧

#124 Feat(client): 프로필, 닉네임 조회 API 연동 및 기본 API환경 구성
  apps/client/.env.example
  apps/client/src/pages/my/components/auth/require-login-section.css.ts
  apps/client/src/pages/my/components/auth/require-login-section.tsx
  apps/client/src/pages/my/hooks/.gitkeep
  apps/client/src/pages/my/hooks/use-user-info.ts
  apps/client/src/pages/my/page/auth/require-login.tsx
  apps/client/src/pages/my/page/profile/my-profile.tsx
  apps/client/src/pages/my/types/.gitkeep
  apps/client/src/shared/apis/.gitkeep
  apps/client/src/shared/apis/api.ts
  apps/client/src/shared/apis/user-queries.ts
  apps/client/src/shared/apis/user.ts
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/router/lazy.ts
  apps/client/src/shared/types/api.ts
  apps/client/src/shared/types/user-response.ts
Labels: ✨ Feature, 민하 🎸

#109 Feat(client): timetable section 컴포넌트 구현
  apps/client/src/pages/time-table/components/booth-open-box/booth-open-box.css.ts
  apps/client/src/pages/time-table/components/booth-open-box/booth-open-box.tsx
  apps/client/src/pages/time-table/components/stage/stage.css.ts
  apps/client/src/pages/time-table/components/stage/stage.tsx
  apps/client/src/pages/time-table/components/time-cell/time-cell.css.ts
  apps/client/src/pages/time-table/components/time-cell/time-cell.tsx
  apps/client/src/pages/time-table/components/time-table-board/time-table-board.css.ts
  apps/client/src/pages/time-table/components/time-table-board/time-table-board.tsx
  apps/client/src/pages/time-table/components/time-table-item/time-table-item.css.ts
  apps/client/src/pages/time-table/components/time-table-item/time-table-item.tsx
  apps/client/src/pages/time-table/components/time-table-section/time-table-section.css.ts
  apps/client/src/pages/time-table/components/time-table-section/time-table-section.tsx
  apps/client/src/pages/time-table/constants/index.ts
  apps/client/src/pages/time-table/types/.gitkeep
  apps/client/src/pages/time-table/types/time-table-info-type.ts
  apps/client/src/pages/time-table/utils/index.ts
  apps/client/src/shared/mocks/time-table.ts
  apps/client/src/shared/utils/.gitkeep
  packages/design-system/src/styles/tokens/border.ts
  packages/design-system/src/styles/tokens/z-index.ts
Labels: ✨ Feature, 한서 🎤

#125 Feat(client): 마이페이지에서 공연 클릭시 detail 페이지 라우팅 연결
  apps/client/src/pages/my/components/confeti/conteti-section.tsx
  apps/client/src/pages/my/page/confeti/confeti-detail.tsx
  apps/client/src/pages/time-table/page/add-festival.tsx
  apps/client/src/shared/mocks/performance-data.ts
  packages/design-system/.storybook/preview.tsx
  packages/design-system/src/components/artist-card/artist-card.stories.tsx
  packages/design-system/src/components/festival-card/festival-card.css.ts
  packages/design-system/src/components/festival-card/festival-card.tsx
  packages/design-system/src/components/header/header.stories.tsx
Labels: ✨ Feature, 한서 🎤

#133 Feat(client): 검색 페이지 목록에서 공연 상세 페이지로 라우팅
  apps/client/src/pages/confeti/components/summary.tsx
  apps/client/src/pages/search/components/performance-info.css.ts
  apps/client/src/pages/search/components/performance-info.tsx
  apps/client/src/pages/search/components/performance-section.tsx
  apps/client/src/pages/search/components/title.tsx
  apps/client/src/pages/time-table/hooks/.gitkeep
Labels: ✨ Feature, 채은 🪕

#118 Feat(client): 캘린더 컴포넌트 구현
  .idea/.gitignore
  .idea/35-APPJAM-WEB-CONFETI.iml
  .idea/modules.xml
  .idea/vcs.xml
  apps/client/src/pages/confeti/components/summary.tsx
  apps/client/src/pages/time-table/components/calender/calender.css.ts
  apps/client/src/pages/time-table/components/calender/calender.tsx
  apps/client/src/pages/time-table/components/info/info-button.css.ts
  apps/client/src/pages/time-table/components/info/info-button.tsx
  apps/client/src/pages/time-table/hooks/use-button-selection.ts
  apps/client/src/pages/time-table/hooks/use-data-formatted.ts
  apps/client/src/pages/time-table/mocks/festival-data.ts
  apps/client/src/pages/time-table/page/add-festival.tsx
  apps/client/src/pages/time-table/page/time-table.tsx
  apps/client/src/shared/constants/day.ts
  packages/design-system/src/styles/tokens/border.ts
Labels: ✨ Feature, 지욱 🥁

#139 Refactor(client): 폴더구조 변경 및 코드 리팩토링
  apps/client/src/pages/confeti/components/artist/artist-card.css.ts
  apps/client/src/pages/confeti/components/artist/artist-card.tsx
  apps/client/src/pages/confeti/components/artist/artist-grid.css.ts
  apps/client/src/pages/confeti/components/artist/artist-grid.tsx
  apps/client/src/pages/confeti/components/artist/artist-section.css.ts
  apps/client/src/pages/confeti/components/artist/artist-section.tsx
  apps/client/src/pages/confeti/components/artist/artist-title.css.ts
  apps/client/src/pages/confeti/components/artist/artist-title.tsx
  apps/client/src/pages/confeti/components/button/more-button.css.ts
  apps/client/src/pages/confeti/components/button/more-button.tsx
  apps/client/src/pages/confeti/components/expanded/expanded-section.css.ts
  apps/client/src/pages/confeti/components/expanded/expanded-section.tsx
  apps/client/src/pages/confeti/components/info/info.css.ts
  apps/client/src/pages/confeti/components/info/info.tsx
  apps/client/src/pages/confeti/components/performance/performance-detail.css.ts
  apps/client/src/pages/confeti/components/performance/performance-detail.tsx
  apps/client/src/pages/confeti/components/poster/poster.css.ts
  apps/client/src/pages/confeti/components/poster/poster.tsx
  apps/client/src/pages/confeti/components/summary/summary.css.ts
  apps/client/src/pages/confeti/components/summary/summary.tsx
  apps/client/src/pages/confeti/mocks/confeti-detail.ts
  apps/client/src/pages/confeti/page/concert-detail.tsx
  apps/client/src/pages/confeti/page/festival-detail.tsx
Labels: 🛠️ Refactor, 지욱 🥁

#137 Feat(client): 로딩 페이지 및 Suspense 구현
  apps/client/package.json
  apps/client/src/shared/assets/lotties/confeti-logo-animation.json
  apps/client/src/shared/constants/path.ts
  apps/client/src/shared/pages/.gitkeep
  apps/client/src/shared/pages/loading/loading.css.ts
  apps/client/src/shared/pages/loading/loading.tsx
  apps/client/src/shared/router/global-layout.tsx
  apps/client/src/shared/router/router.tsx
  pnpm-lock.yaml
Labels: ✨ Feature, 다현 🎧

#140 Feat(client): 타임테이블 페이지 퍼블리싱
  apps/client/src/pages/home/page/home.tsx
  apps/client/src/pages/time-table/components/booth-open-box/booth-open-box.tsx
  apps/client/src/pages/time-table/components/calender/calender.tsx
  apps/client/src/pages/time-table/components/edit/edit-floating-button.css.ts
  apps/client/src/pages/time-table/components/edit/edit-floating-button.tsx
  apps/client/src/pages/time-table/components/info/info-button.tsx
  apps/client/src/pages/time-table/constants/index.ts
  apps/client/src/pages/time-table/hooks/use-button-selection.ts
  apps/client/src/pages/time-table/hooks/use-data-formatted.ts
  apps/client/src/pages/time-table/page/empty/empty-festival-page.tsx
  apps/client/src/pages/time-table/page/time-table-layout.tsx
  apps/client/src/pages/time-table/page/time-table.tsx
  apps/client/src/shared/router/lazy.ts
  apps/client/src/shared/router/router.tsx
  packages/design-system/src/components/navigation/navigation.tsx
Labels: ✨ Feature, 한서 🎤

#144 Feat(client): axios 인터셉터 설정
  apps/client/src/shared/apis/api.ts
  apps/client/src/shared/apis/config/http-error.ts
  apps/client/src/shared/apis/config/index.d.ts
  apps/client/src/shared/apis/config/instance.ts
  apps/client/src/shared/apis/config/interceptor.ts
  apps/client/src/shared/apis/user.ts
  apps/client/src/shared/constants/api.ts
Labels: ✨ Feature, 지욱 🥁

#143 Feat(client): 좋아요 API 공통 로직 훅 구현 및 아티스트 좋아요 추가/삭제 API 연동
  apps/client/src/pages/my/hooks/use-user-info.ts
  apps/client/src/pages/search/components/artist-info.tsx
  apps/client/src/pages/search/components/artist-section.tsx
  apps/client/src/pages/search/mocks/searched-artist-data.ts
  apps/client/src/shared/apis/like/like-queries.ts
  apps/client/src/shared/apis/like/like.ts
  apps/client/src/shared/apis/user/user-queries.ts
  apps/client/src/shared/apis/user/user.ts
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/hooks/.gitkeep
  apps/client/src/shared/hooks/use-like-mutation.ts
  apps/client/src/shared/mocks/artist-data.ts
  apps/client/src/shared/mocks/artists-data.ts
  apps/client/src/shared/types/api.ts
  packages/design-system/src/icons/src/BtnHeart.tsx
  packages/design-system/src/icons/src/index.ts
Labels: ✨ Feature, 민하 🎸

#149 Fix(client): 페스티벌 추가 페이지 기능 수정
  apps/client/src/pages/time-table/hooks/use-festival-selection.ts
  apps/client/src/pages/time-table/page/add-festival.tsx
  packages/design-system/src/components/festival-card/festival-card.tsx
Labels: 👾 Fix, 채은 🪕

#156 Feat(design-system): 헤더 상단 고정 기능 추가
  packages/design-system/src/components/header/header.css.ts
  packages/design-system/src/styles/tokens/z-index.ts
Labels: 👾 Fix, 민하 🎸

#153 Feat(client): 이미지 저장 기능 구현
  apps/client/package.json
  apps/client/src/pages/home/page/home.tsx
  apps/client/src/pages/time-table/components/edit/edit-floating-button.css.ts
  apps/client/src/pages/time-table/components/time-cell/time-cell.css.ts
  apps/client/src/pages/time-table/components/time-table-board/time-table-board.css.ts
  apps/client/src/pages/time-table/components/time-table-board/time-table-board.tsx
  apps/client/src/pages/time-table/components/time-table-item/time-table-item.css.ts
  apps/client/src/pages/time-table/components/time-table-section/time-table-section.css.ts
  apps/client/src/pages/time-table/components/time-table-section/time-table-section.tsx
  apps/client/src/pages/time-table/constants/index.ts
  apps/client/src/pages/time-table/hooks/use-image-download.ts
  apps/client/src/pages/time-table/page/time-table.tsx
  pnpm-lock.yaml
Labels: ✨ Feature, 한서 🎤

#146 Feat(client): 공연 정보 조회 api 연동
  apps/client/src/pages/confeti/components/artist/artist-card.css.ts
  apps/client/src/pages/confeti/components/artist/artist-card.tsx
  apps/client/src/pages/confeti/hooks/.gitkeep
  apps/client/src/pages/confeti/hooks/use-concert-detail.ts
  apps/client/src/pages/confeti/hooks/use-festival-detail.ts
  apps/client/src/pages/confeti/page/concert-detail.tsx
  apps/client/src/pages/confeti/page/festival-detail.tsx
  apps/client/src/shared/apis/confeti-detail/concert.ts
  apps/client/src/shared/apis/confeti-detail/festival.ts
  apps/client/src/shared/apis/confeti-detail/performance-queries.ts
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/types/concert-response.ts
  apps/client/src/shared/types/festival-response.ts
  apps/client/src/shared/types/performance-common.ts
  packages/design-system/src/icons/assets/ic_artist_non.svg
  packages/design-system/src/icons/src/IcArtistNon.tsx
  packages/design-system/src/icons/src/index.ts
Labels: ✨ Feature, 다현 🎧

#161 Fix(client, design-system): 페스티벌 추가페이지 스타일 에러 해결
  apps/client/src/pages/time-table/page/add-festival.css.ts
  apps/client/src/pages/time-table/page/add-festival.tsx
  packages/design-system/src/components/header/header.tsx
Labels: 👾 Fix, 한서 🎤

#164 Feat(client): 타임테이블 EditFloatingButton 기능 구현
  apps/client/src/pages/time-table/components/calender/calender.css.ts
  apps/client/src/pages/time-table/components/calender/calender.tsx
  apps/client/src/pages/time-table/components/edit/edit-floating-button.css.ts
  apps/client/src/pages/time-table/components/edit/edit-floating-button.tsx
  apps/client/src/pages/time-table/components/time-table-board/time-table-board.tsx
  apps/client/src/pages/time-table/components/time-table-item/time-table-item.tsx
  apps/client/src/pages/time-table/hooks/use-button-selection.ts
  apps/client/src/pages/time-table/hooks/use-disabled-scroll.ts
  apps/client/src/pages/time-table/hooks/use-edit-mode.ts
  apps/client/src/pages/time-table/hooks/use-scroll-position.ts
  apps/client/src/pages/time-table/page/time-table.tsx
  apps/client/src/pages/time-table/types/time-table-info-type.ts
Labels: ✨ Feature, 민하 🎸

#159 Feat(client): festival 좋아요 추가/삭제 api 연동
  apps/client/.env.example
  apps/client/src/pages/confeti/components/summary/summary.css.ts
  apps/client/src/pages/confeti/components/summary/summary.tsx
  apps/client/src/pages/confeti/mocks/confeti-detail.ts
  apps/client/src/pages/confeti/page/concert-detail.tsx
  apps/client/src/pages/confeti/page/festival-detail.tsx
  apps/client/src/shared/apis/like/like-queries.ts
  apps/client/src/shared/apis/like/like.ts
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/hooks/use-like-mutation.ts
Labels: ✨ Feature, 한서 🎤

#166 Feat(client): my-artists 조회 api 연결
  apps/client/src/pages/my/components/artist/artist-section.tsx
  apps/client/src/pages/my/hooks/use-my-artist.ts
  apps/client/src/pages/my/page/artist/artist-detail.tsx
  apps/client/src/pages/my/page/profile/my-profile.tsx
  apps/client/src/shared/apis/user/user-queries.ts
  apps/client/src/shared/apis/user/user.ts
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/types/user-response.ts
  packages/design-system/src/components/artist-card/artist-card.css.ts
Labels: ✨ Feature, 한서 🎤

#171 Feat(client): 검색 페이지 기능 구현
  apps/client/src/pages/search/components/artist-section.css.ts
  apps/client/src/pages/search/components/artist-section.tsx
  apps/client/src/pages/search/components/notice-section.tsx
  apps/client/src/pages/search/components/performance-count-section.tsx
  apps/client/src/pages/search/components/performance-section.tsx
  apps/client/src/pages/search/hooks/use-search-data.ts
  apps/client/src/pages/search/hooks/use-search-logic.ts
  apps/client/src/pages/search/hooks/use-search.ts
  apps/client/src/pages/search/hooks/use-sorted-performances.ts
  apps/client/src/pages/search/page/search.tsx
  apps/client/src/shared/apis/like/like.ts
  apps/client/src/shared/apis/search/search-queries.ts
  apps/client/src/shared/apis/search/search.ts
  apps/client/src/shared/apis/user/user.ts
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/types/search-reponse.ts
  packages/design-system/src/components/search-bar/SearchBar.stories.ts
  packages/design-system/src/components/search-bar/search-bar.tsx
Labels: ✨ Feature, 지욱 🥁

#175 Feat(client): 글로벌 그림자 스타일 추가
  packages/design-system/src/styles/global.css.ts
  packages/design-system/src/styles/tokens/box-shadow.ts
Labels: ✨ Feature, 지욱 🥁

#165 Feat(client): 관심있는 공연 목록 조회 API 연동
  apps/client/src/pages/my/components/confeti/confeti-section.tsx
  apps/client/src/pages/my/components/confeti/conteti-section.tsx
  apps/client/src/pages/my/hooks/use-performance-detail.ts
  apps/client/src/pages/my/page/confeti/confeti-more.css.ts
  apps/client/src/pages/my/page/confeti/confeti-more.tsx
  apps/client/src/pages/my/page/profile/my-profile.tsx
  apps/client/src/shared/apis/user/user-queries.ts
  apps/client/src/shared/apis/user/user.ts
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/mocks/performance-data.ts
  apps/client/src/shared/router/lazy.ts
  apps/client/src/shared/types/performance-response.ts
  apps/client/src/shared/types/user-response.ts
Labels: ✨ Feature, 채은 🪕

#177 Feat(client): 페이지 이동시 스크롤 상단고정 기능 구현
  apps/client/public/favicon.svg
  apps/client/src/shared/router/global-layout.tsx
  apps/client/src/shared/router/scroll-to-top.tsx
Labels: ✨ Feature, 민하 🎸

#179 Feat(client): 404 Error 페이지 추가
  apps/client/src/shared/pages/error/error.css.ts
  apps/client/src/shared/pages/error/error.tsx
  packages/design-system/src/icons/assets/ic_error_404.svg
  packages/design-system/src/icons/src/IcError404.tsx
  packages/design-system/src/icons/src/index.ts
Labels: ✨ Feature, 민하 🎸

#186 Fix(client): EditFloatingButton 웹에서 우측하단 고정안되는 이슈 해결
  apps/client/src/pages/time-table/components/edit/edit-floating-button.css.ts
  apps/client/src/pages/time-table/page/time-table.tsx
Labels: 👾 Fix, 민하 🎸

#182 Feat: 타임테이블 페스티벌 삭제 api 연결
  apps/client/src/pages/time-table/components/edit/edit-floating-button.tsx
  apps/client/src/pages/time-table/components/info/delete-button.css.ts
  apps/client/src/pages/time-table/components/info/delete-button.tsx
  apps/client/src/pages/time-table/components/info/info-button.css.ts
  apps/client/src/pages/time-table/components/info/info-button.tsx
  apps/client/src/pages/time-table/hooks/use-timetable-festival-mutation.ts
  apps/client/src/pages/time-table/page/time-table.css.ts
  apps/client/src/pages/time-table/page/time-table.tsx
  apps/client/src/shared/apis/time-table/festival-timetable-queries.ts
  apps/client/src/shared/apis/time-table/festival-timetable.ts
  apps/client/src/shared/constants/api.ts
  packages/design-system/src/icons/assets/btn_festival_delete.svg
  packages/design-system/src/icons/src/BtnClose.tsx
  packages/design-system/src/icons/src/BtnFestivalDelete.tsx
  packages/design-system/src/icons/src/index.ts
Labels: ✨ Feature, 한서 🎤

#192 Feat(client): 예정된 페스티벌 목록 조회 API 연동
  apps/client/src/pages/time-table/hooks/use-get-festival-to-add.ts
  apps/client/src/pages/time-table/page/add-festival.tsx
  apps/client/src/shared/apis/confeti-detail/concert.ts
  apps/client/src/shared/apis/confeti-detail/confeti.ts
  apps/client/src/shared/apis/confeti-detail/get-festival-to-add-queries.ts
  apps/client/src/shared/apis/confeti-detail/get-festival-to-add.ts
  apps/client/src/shared/apis/confeti-detail/performance-queries.ts
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/types/get-festival-to-add-response.ts
  apps/client/src/shared/utils/use-infinite-scroll.ts
Labels: ✨ Feature, 다현 🎧

#195 Feat(design-system): svgo를 통한 최적화
  apps/client/src/pages/time-table/page/add-festival.tsx
  packages/design-system/src/icons/assets/btn_account_black_24.svg
  packages/design-system/src/icons/assets/btn_account_gray_24.svg
  packages/design-system/src/icons/assets/btn_add_gray_24.svg
  packages/design-system/src/icons/assets/btn_arrow_left_20.svg
  packages/design-system/src/icons/assets/btn_arrow_left_24.svg
  packages/design-system/src/icons/assets/btn_close.svg
  packages/design-system/src/icons/assets/btn_festival_delete.svg
  packages/design-system/src/icons/assets/btn_heart_default_24.svg
  packages/design-system/src/icons/assets/btn_heart_filled_24.svg
  packages/design-system/src/icons/assets/btn_search_black_24.svg
  packages/design-system/src/icons/assets/btn_search_g900_24.svg
  packages/design-system/src/icons/assets/ic_arrow_down_gray_16.svg
  packages/design-system/src/icons/assets/ic_arrow_gray_16.svg
  packages/design-system/src/icons/assets/ic_arrow_up_black_30.svg
  packages/design-system/src/icons/assets/ic_arrow_up_gray_16.svg
  packages/design-system/src/icons/assets/ic_arrow_white_12.svg
  packages/design-system/src/icons/assets/ic_artist_non.svg
  packages/design-system/src/icons/assets/ic_error_404.svg
  packages/design-system/src/icons/assets/ic_exclamation_circle_outlined_32.svg
  packages/design-system/src/icons/assets/ic_festival_gray.svg
  packages/design-system/src/icons/assets/ic_float_delete_24.svg
  packages/design-system/src/icons/assets/ic_float_edit_24.svg
  packages/design-system/src/icons/assets/ic_float_edit_lime_24.svg
  packages/design-system/src/icons/assets/ic_indicator_active.svg
  packages/design-system/src/icons/assets/ic_indicator_default.svg
  packages/design-system/src/icons/assets/ic_link.svg
  packages/design-system/src/icons/assets/ic_place_gray_14.svg
  packages/design-system/src/icons/assets/ic_select.svg
  packages/design-system/src/icons/assets/ic_sic_gray_18.svg
  packages/design-system/src/icons/assets/ic_time_gray_14.svg
  packages/design-system/src/icons/assets/ic_timetable_float_close.svg
  packages/design-system/src/icons/assets/ic_timetable_float_finish.svg
  packages/design-system/src/icons/assets/ic_toast_info_24.svg
  packages/design-system/src/icons/assets/logo_footer.svg
  packages/design-system/src/icons/assets/logo_main.svg
  packages/design-system/src/icons/assets/logo_symbol.svg
Labels: 🌎 Deploy, 민하 🎸, 한서 🎤

#183 Fix(client): iOS에서 input창 확대 되는 이슈 해결
  apps/client/index.html
  apps/client/src/pages/search/hooks/use-search-logic.ts
  apps/client/src/pages/search/page/search.tsx
  packages/design-system/src/components/search-bar/search-bar.tsx
Labels: 👾 Fix, 다현 🎧

#198 Fix: my-artists 스타일 수정
  apps/client/public/images/thumbnail.jpeg
  apps/client/src/pages/my/components/artist/artist-section.css.ts
  apps/client/src/pages/my/page/artist/artist-detail.css.ts
Labels: 👾 Fix, 한서 🎤

#197 Feat(client) : 타임 테이블 페이지 시간표 api 연동
  apps/client/public/images/tumbnail.jpeg
  apps/client/src/pages/time-table/components/calender/calender.tsx
  apps/client/src/pages/time-table/components/edit/edit-floating-button.css.ts
  apps/client/src/pages/time-table/components/edit/edit-floating-button.tsx
  apps/client/src/pages/time-table/components/info/info-button.tsx
  apps/client/src/pages/time-table/components/time-table-board/time-table-board.tsx
  apps/client/src/pages/time-table/components/time-table-item/time-table-item.css.ts
  apps/client/src/pages/time-table/components/time-table-item/time-table-item.tsx
  apps/client/src/pages/time-table/hooks/use-button-selection.ts
  apps/client/src/pages/time-table/hooks/use-festival-data.ts
  apps/client/src/pages/time-table/hooks/use-festival-timetables.ts
  apps/client/src/pages/time-table/hooks/use-timetable-festival-mutation.ts
  apps/client/src/pages/time-table/page/time-table.tsx
  apps/client/src/pages/time-table/types/time-table-info-type.ts
  apps/client/src/shared/apis/time-table/festival-button-queries.ts
  apps/client/src/shared/apis/time-table/festival-button.ts
  apps/client/src/shared/apis/time-table/festival-timetable-queries.ts
  apps/client/src/shared/apis/time-table/festival-timetable.ts
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/mocks/time-table.ts
  apps/client/src/shared/types/festival-timetable-response.ts
Labels: ✨ Feature, 지욱 🥁

#208 Fix(client): 마이페이지 아티스트 없을 경우 이슈 해결
  apps/client/src/pages/confeti/mocks/confeti-detail.ts
  apps/client/src/pages/my/components/artist/artist-section.tsx
  apps/client/src/pages/my/components/artist/no-artist-section.css.ts
  apps/client/src/pages/my/components/profile/box.css.ts
  apps/client/src/pages/my/hooks/use-my-favorites.ts
  apps/client/src/pages/my/page/artist/artist-detail.tsx
  apps/client/src/pages/my/page/profile/my-profile.tsx
  apps/client/src/pages/search/mocks/searched-artist-data.ts
  apps/client/src/shared/mocks/artist-data.ts
  apps/client/src/shared/types/user-response.ts
Labels: 👾 Fix, 채은 🪕

#216 Feat(client): 마이페이지 관심목록 데이터 추가
  apps/client/src/pages/my/page/artist/artist-more.css.ts
  apps/client/src/pages/my/page/artist/artist-more.tsx
  apps/client/src/pages/my/page/confeti/confeti-more.tsx
  apps/client/src/shared/mocks/artists-data.ts
  apps/client/src/shared/mocks/performance-data.ts
  apps/client/src/shared/router/lazy.ts
Labels: ✨ Feature, 민하 🎸

#205 Feat(client): 콘서트 좋아요 추가, 삭제 api 연결
  apps/client/src/pages/confeti/components/summary/summary.tsx
  apps/client/src/pages/confeti/page/concert-detail.tsx
  apps/client/src/pages/confeti/page/festival-detail.tsx
  apps/client/src/shared/apis/like/like.ts
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/hooks/use-like-mutation.ts
Labels: ✨ Feature, 채은 🪕

#220 Fix(client): 검색 페이지 버그 수정
  apps/client/src/pages/search/hooks/use-search-logic.ts
  apps/client/src/shared/apis/search/search-queries.ts
  apps/client/src/shared/hooks/use-like-mutation.ts
  packages/design-system/src/components/header/header.tsx
  packages/design-system/src/components/search-bar/search-bar.css.ts
  packages/design-system/src/components/search-bar/search-bar.tsx
Labels: ✨ Feature, 지욱 🥁

#223 Fix(design-system): 아티스트 이미지 깨짐 현상 해결
  packages/design-system/src/components/artist-card/artist-card.css.ts
Labels: 👾 Fix, 민하 🎸

#227 Feat(design-system): LikeButton 컴포넌트 추가
  apps/client/src/pages/confeti/components/summary/summary.css.ts
  apps/client/src/pages/confeti/components/summary/summary.tsx
  apps/client/src/pages/search/components/artist-info.css.ts
  apps/client/src/pages/search/components/artist-info.tsx
  packages/design-system/src/components/index.ts
  packages/design-system/src/components/like-button/like-button.css.ts
  packages/design-system/src/components/like-button/like-button.stories.tsx
  packages/design-system/src/components/like-button/like-button.tsx
Labels: ✨ Feature, 민하 🎸

#225 Fix(client): 페스티벌 토스트 기능 수정
  apps/client/src/pages/time-table/page/add-festival.tsx
Labels: 👾 Fix, 다현 🎧

#206 Feat(client): timetable festival 추가 api 연결
  apps/client/public/images/tumbnail.jpeg
  apps/client/src/pages/time-table/components/edit/edit-floating-button.tsx
  apps/client/src/pages/time-table/hooks/use-festival-delete.ts
  apps/client/src/pages/time-table/hooks/use-timetable-festival-mutation.ts
  apps/client/src/pages/time-table/page/add-festival.css.ts
  apps/client/src/pages/time-table/page/add-festival.tsx
  apps/client/src/pages/time-table/page/time-table.tsx
  apps/client/src/shared/apis/time-table/festival-button.ts
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/types/festival-timetable-response.ts
Labels: ✨ Feature, 한서 🎤

#228 Feat(client): 비로그인 상태로 좋아요 클릭시 토스트 출력 추가
  apps/client/src/pages/search/components/artist-info.tsx
  apps/client/src/shared/router/protected-route.tsx
  apps/client/src/shared/utils/check-is-not-logged-in.ts
  packages/design-system/src/components/like-button/like-button.tsx
Labels: ✨ Feature, 다현 🎧

#207 Fix(design-system): progress-bar 및 ticketing-carousel 글자 간격 조정
  packages/design-system/src/components/ticketing-carousel/progress-bar/progress-bar.css.ts
  packages/design-system/src/components/ticketing-carousel/ticketing-carousel.css.ts
Labels: 👾 Fix, 지욱 🥁

#231 Refactor: 타임테이블 레이아웃 수정
  apps/client/src/pages/time-table/components/stage/stage.tsx
  apps/client/src/pages/time-table/components/time-cell/time-cell.css.ts
  apps/client/src/pages/time-table/components/time-table-item/time-table-item.css.ts
  apps/client/src/pages/time-table/components/time-table-item/time-table-item.tsx
  apps/client/src/pages/time-table/constants/index.ts
Labels: 👾 Fix, 민하 🎸

#232 Deploy: vercel.json파일 추가
  apps/client/vercel.json
Labels: 🌎 Deploy, 민하 🎸

#237 Fix(client): (QA/2) 포스터 border-radius 수정
  apps/client/src/pages/confeti/components/poster/poster.css.ts
Labels: 👾 Fix, 채은 🪕

#239 Fix(design-system): 메인페이지 배너 상단 수정, 404 페이지 글자 크기 변경
  apps/client/src/shared/pages/error/error.css.ts
  packages/design-system/src/components/performance-carousel/dots.css.ts
  packages/design-system/src/components/performance-carousel/performance-carousel.css.ts
  packages/design-system/src/components/performance-carousel/performance-carousel.tsx
  packages/design-system/src/components/performance-carousel/slick.css.ts
  packages/design-system/src/styles/tokens/font-styles.ts
  packages/design-system/src/styles/tokens/typography.ts
Labels: 👾 Fix, 한서 🎤

#238 Fix(client): 유저 및 페스티벌 데이터 수정
  apps/client/src/pages/home/page/home.tsx
  apps/client/src/shared/mocks/performance-data.ts
  packages/design-system/src/components/like-button/like-button.css.ts
Labels: 👾 Fix, 민하 🎸

#244 Fix(client): 타임테이블 페이지 로드시 편집하기 버튼 위로 올라가는 현상 수정
  apps/client/src/pages/time-table/hooks/use-scroll-position.ts
Labels: 👾 Fix, 민하 🎸

#249 Fix(client): 페스티벌 삭제 로직 수정
  apps/client/src/pages/time-table/components/edit/edit-floating-button.tsx
  apps/client/src/pages/time-table/components/empty/empty-festival-section.tsx
  apps/client/src/pages/time-table/hooks/use-festival-delete.ts
  apps/client/src/pages/time-table/page/time-table.tsx
  apps/client/src/shared/router/router.tsx
Labels: 👾 Fix, 한서 🎤

#245 Fix(design-system): 디데이 계산 로직 수정
  packages/design-system/src/components/ticketing-carousel/hooks/use-data-format.ts
Labels: 👾 Fix, 채은 🪕

#247 Feat(client): 최신 등록 순 공연 정보 조회 API 연동
  apps/client/src/pages/home/hooks/use-latest-performances.ts
  apps/client/src/pages/home/page/home.tsx
  apps/client/src/shared/apis/carousel/carousel-queries.ts
  apps/client/src/shared/apis/carousel/performances.ts
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/types/performance-response.ts
  packages/design-system/src/components/performance-carousel/performance-carousel.tsx
Labels: ✨ Feature, 채은 🪕

#252 Fix(design-system): 상단 배너 스타일 추가
  packages/design-system/src/components/performance-carousel/performance-carousel.tsx
Labels: 👾 Fix, 한서 🎤

#254 Feat(client): 타임테이블 시간표 수정 API 연동
  apps/client/src/pages/time-table/components/edit/edit-floating-button.tsx
  apps/client/src/pages/time-table/components/time-table-board/time-table-board.tsx
  apps/client/src/pages/time-table/components/time-table-item/time-table-item.css.ts
  apps/client/src/pages/time-table/components/time-table-item/time-table-item.tsx
  apps/client/src/pages/time-table/hooks/use-edit-mode.ts
  apps/client/src/pages/time-table/hooks/use-patch-time-table-mutation.ts
  apps/client/src/pages/time-table/page/time-table.tsx
  apps/client/src/shared/apis/time-table/festival-button.ts
  apps/client/src/shared/apis/time-table/festival-timetable.ts
  apps/client/src/shared/types/timetable-response.ts
Labels: ✨ Feature, 지욱 🥁, 민하 🎸

#259 Fix(client): 관심 아티스트 목록 수정
  apps/client/src/pages/my/page/profile/my-profile.tsx
Labels: 👾 Fix, 민하 🎸

#256 Feat(client): 검색된 아티스트 공연 정보 조회 구현
  apps/client/src/pages/search/components/performance-section.tsx
  apps/client/src/pages/search/hooks/use-search-data.ts
  apps/client/src/pages/search/mocks/searched-performance-data.ts
  apps/client/src/pages/search/page/search.tsx
  apps/client/src/shared/apis/search/search-queries.ts
  apps/client/src/shared/apis/search/search.ts
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/types/search-reponse.ts
Labels: ✨ Feature, 다현 🎧

#257 Feat(client): 아티스트 선택하기 버튼 기능구현
  apps/client/src/pages/home/page/home.tsx
  apps/client/src/pages/my/components/artist/no-artist-section.tsx
  apps/client/src/pages/time-table/components/edit/edit-floating-button.tsx
Labels: ✨ Feature, 지욱 🥁

#267 Fix(client): (QA/4) 비로그인 상태로 홈화면 이동시 에러 수정
  apps/client/src/pages/home/page/home.tsx
  apps/client/src/pages/my/hooks/use-my-favorites.ts
  apps/client/src/pages/my/hooks/use-user-info.ts
  apps/client/src/pages/my/page/artist/artist-more.tsx
  apps/client/src/pages/my/page/confeti/confeti-more.tsx
  apps/client/src/pages/my/page/profile/my-profile.tsx
Labels: 👾 Fix, 다현 🎧

#263 Fix(client): (QA/4) 공연 목록 좋아요 연결, 비로그인 토스트 연결
  apps/client/src/pages/search/components/performance-info.css.ts
  apps/client/src/pages/search/components/performance-info.tsx
  apps/client/src/pages/search/components/performance-section.tsx
  apps/client/src/pages/time-table/page/add-festival.tsx
  apps/client/src/shared/mocks/performance-data.ts
  apps/client/src/shared/types/performance-response.ts
  apps/client/src/shared/types/search-reponse.ts
  apps/client/src/shared/types/user-response.ts
  packages/design-system/src/components/festival-card/festival-card.tsx
  packages/design-system/src/components/performance-carousel/performance-carousel.tsx
Labels: 👾 Fix, 한서 🎤

#265 Fix(design-system): 상세 페이지 플로팅 버튼 포지션 수정
  apps/client/src/pages/confeti/page/concert-detail.tsx
  packages/design-system/src/components/floating-button/floating-button.css.ts
Labels: 👾 Fix, 지욱 🥁

#264 Fix(design-system): (QA/4) 상단 배너 클릭 시 상세 페이지로 이동
  packages/design-system/src/components/performance-carousel/performance-carousel.css.ts
  packages/design-system/src/components/performance-carousel/performance-carousel.tsx
Labels: 👾 Fix, 채은 🪕

#261 Fix(design-system): 하단 배너 QA 반영
  packages/design-system/src/components/button/button.tsx
  packages/design-system/src/components/index.ts
  packages/design-system/src/components/performance-carousel/performance-carousel.stories.tsx
  packages/design-system/src/components/performance-carousel/performance-carousel.tsx
  packages/design-system/src/components/ticketing-carousel/info-button/info-button.css.ts
  packages/design-system/src/components/ticketing-carousel/mocks/bottom-banner-data.ts
  packages/design-system/src/components/ticketing-carousel/progress-bar/progress-bar.css.ts
  packages/design-system/src/components/ticketing-carousel/progress-bar/progress-bar.stories.tsx
  packages/design-system/src/components/ticketing-carousel/ticketing-carousel.css.ts
  packages/design-system/src/icons/assets/ic_link.svg
  packages/design-system/src/icons/src/IcLink.tsx
  packages/design-system/src/icons/src/index.ts
  packages/design-system/tsconfig.json
Labels: ✨ Feature, 지욱 🥁

#272 Fix: 비로그인 상세페이지 이동할 수 있도록 수정, 상단 배너 클릭시 outline 제거
  apps/client/src/pages/search/components/performance-info.tsx
  packages/design-system/src/components/performance-carousel/performance-carousel.css.ts
  packages/design-system/src/components/performance-carousel/performance-carousel.tsx
Labels: 👾 Fix, 한서 🎤

#277 Feat(client): 아티스트 없을 때 검색화면 예외처리 추가
  apps/client/src/pages/search/page/search.tsx
Labels: 👾 Fix, 민하 🎸

#285 Fix(client): ProgressBar 패딩 값 조정
  packages/design-system/src/components/ticketing-carousel/progress-bar/progress-bar.css.ts
  packages/design-system/src/components/ticketing-carousel/ticketing-carousel.css.ts
Labels: 👾 Fix, 다현 🎧

#282 Fix(client): 타임테이블 이미지 저장 개선
  apps/client/src/pages/time-table/components/time-table-board/time-table-board.tsx
  apps/client/src/pages/time-table/hooks/use-button-selection.ts
  apps/client/src/pages/time-table/page/time-table.tsx
  packages/design-system/src/components/ticketing-carousel/ticketing-carousel.css.ts
  packages/design-system/src/components/ticketing-carousel/ticketing-carousel.tsx
Labels: 👾 Fix, 지욱 🥁

#283 Fix: (QA/4) 더보기 버튼 4개 이상일 때만 뜨도록 수정
  apps/client/src/pages/my/page/profile/my-profile.tsx
Labels: 👾 Fix, 채은 🪕

#279 Feat(client): 애니메이션 추가를 통한 UX개선
  apps/client/src/pages/confeti/components/expanded/expanded-section.css.ts
  apps/client/src/pages/confeti/components/expanded/expanded-section.tsx
  apps/client/src/pages/confeti/components/performance/performance-detail.css.ts
  apps/client/src/pages/time-table/components/info/info-button.css.ts
  apps/client/src/pages/time-table/components/info/info-button.tsx
  apps/client/src/pages/time-table/page/time-table.tsx
Labels: ✨ Feature, 민하 🎸

#280 Fix(client): 공연 정보 조회 무한 스크롤 해결 및 공연 개수 api 연결
  apps/client/src/pages/search/hooks/use-search-data.ts
  apps/client/src/pages/search/page/search.tsx
  apps/client/src/pages/time-table/page/add-festival.tsx
  apps/client/src/shared/apis/search/search-queries.ts
  apps/client/src/shared/apis/search/search.ts
  apps/client/src/shared/types/search-reponse.ts
Labels: 👾 Fix, 다현 🎧

#286 Fix(client): 검색 페이지 불필요한 변수 제거 및 코드 정리
  apps/client/src/pages/search/page/search.tsx
Labels: 👾 Fix, 민하 🎸

#281 Fix: (QA/4) 페스티벌 삭제 시 이슈 해결
  README.md
  apps/client/src/pages/confeti/components/expanded/expanded-section.css.ts
  apps/client/src/pages/time-table/components/add/add-button.tsx
  apps/client/src/pages/time-table/components/edit/edit-floating-button.tsx
  apps/client/src/pages/time-table/components/info/info-button.tsx
  apps/client/src/pages/time-table/hooks/use-timetable-festival-mutation.ts
  apps/client/src/pages/time-table/page/time-table.tsx
  apps/client/src/shared/types/festival-timetable-response.ts
Labels: 👾 Fix, 한서 🎤

#291 Fix(client): 날짜 형식 변환 로직 수정
  packages/design-system/src/components/ticketing-carousel/hooks/use-data-format.ts
Labels: 👾 Fix, 지욱 🥁

#288 Fix(client): description width 값 수정
  packages/design-system/src/components/ticketing-carousel/ticketing-carousel.css.ts
Labels: 👾 Fix, 다현 🎧

#292 Fix: (QA/4) 플로팅 버튼 삭제하기 버그 수정
  apps/client/src/pages/time-table/components/edit/edit-floating-button.tsx
  apps/client/src/pages/time-table/page/time-table.tsx
Labels: 👾 Fix, 한서 🎤

#294 Fix(client): 콘서트 더보기 버튼 기능 수정
  apps/client/src/pages/confeti/components/artist/artist-section.tsx
  apps/client/src/pages/confeti/components/performance/performance-detail.css.ts
  apps/client/src/pages/confeti/page/concert-detail.tsx
  packages/design-system/src/components/ticketing-carousel/ticketing-carousel.css.ts
Labels: ✨ Feature, 지욱 🥁

#299 Docs: README 업데이트
  README.md
Labels: 📑 Docs, 민하 🎸
