Repository team-confeti/confeti-client, pull requests merged in 2025-08, with the labels that each got.

#643 Fix(client): 온보딩 status 변경 된 스펙 반영
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/router/onboarding-guard.tsx
  apps/client/src/shared/types/onboard-response.ts
Labels: 👾 Fix, 지욱 🥁

#645 Fix(client): 타임테이블 이미지 저장기능 개선
  apps/client/src/pages/timetable/components/timetable-actions/timetable-actions.tsx
  apps/client/src/pages/timetable/hooks/use-disabled-scroll.ts
  apps/client/src/pages/timetable/hooks/use-festival-data.ts
  apps/client/src/pages/timetable/hooks/use-image-download.ts
  apps/client/src/pages/timetable/hooks/use-patch-time-table-mutation.ts
  apps/client/src/pages/timetable/page/timetable-content/timetable-content.tsx
Labels: 👾 Fix, 민하 🎸

#640 Fix(client): avatar 컴포넌트 클릭 false 처리 및 morebutton 조건 수정
  apps/client/src/pages/performance/components/artist/festival-artist-section.tsx
Labels: 👾 Fix, 지욱 🥁

#638 Feat: CI 환경 내 TurboRepo 캐시 액션 추가
  .github/workflows/ci.yml
Labels: ✨ Feature, 민하 🎸

#647 Refactor(client): 토큰 재발급 로직 수정
  apps/client/src/pages/onboarding/hooks/use-onboard-mutation.ts
  apps/client/src/shared/apis/auth/auth-mutation.ts
  apps/client/src/shared/constants/api.ts
Labels: 🛠️ Refactor, 민하 🎸
