Repository team-confeti/confeti-client, pull requests merged in 2025-06, with the labels that each got.

#550 Refactor(client): query key 구조 정리 및 staleTime 설정
  apps/client/src/pages/time-table/hooks/use-get-festival-to-add.ts
  apps/client/src/pages/time-table/page/add-festival/add-festival.tsx
  apps/client/src/shared/apis/home/home-queries.ts
  apps/client/src/shared/apis/my-history/my-setlist-queries.ts
  apps/client/src/shared/apis/my-history/my-timetable-queries.ts
  apps/client/src/shared/apis/performance/performance-queries.ts
  apps/client/src/shared/apis/time-table/festival-timetable-queries.ts
  apps/client/src/shared/apis/user/user-queries.ts
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/constants/query-key.ts
Labels: 🛠️ Refactor, 민하 🎸

#561 Feat(client): 페스티벌 추가 없는 경우 페이지 제작
  apps/client/src/pages/timetable/page/empty/empty-festival-section.tsx
  apps/client/src/pages/timetable/page/no-upcoming-festival/no-upcoming-festival.css.ts
  apps/client/src/pages/timetable/page/no-upcoming-festival/no-upcoming-festival.tsx
  apps/client/src/pages/timetable/page/timetable-layout.tsx
  apps/client/src/shared/constants/links.ts
  apps/client/src/shared/router/lazy.ts
  apps/client/src/shared/router/path.ts
  apps/client/src/shared/router/router.tsx
Labels: ✨ Feature, 채은 🪕

#574 Refactor(client) : 로띠 파일 변경 및 일부 압축
  apps/client/src/pages/onboarding/components/onboarding-complete.tsx
  apps/client/src/shared/assets/lotties/confeti-logo-animation.json
Labels: 🛠️ Refactor, 지욱 🥁

#569 Fix(client): 타임테이블 오류 해결
  apps/client/src/pages/timetable/components/calender/calender.tsx
  apps/client/src/pages/timetable/components/festival-selector/festival-button.css.ts
  apps/client/src/pages/timetable/components/festival-selector/festival-button.tsx
  apps/client/src/pages/timetable/components/timetable-board/booth-open-box.css.ts
  apps/client/src/pages/timetable/components/timetable-board/time-cell.css.ts
  apps/client/src/pages/timetable/components/timetable-board/timetable-board.css.ts
  apps/client/src/pages/timetable/components/timetable-board/timetable-item.css.ts
  apps/client/src/pages/timetable/components/timetable-board/timetable-item.tsx
  apps/client/src/pages/timetable/constants/index.ts
  apps/client/src/pages/timetable/hooks/use-data-formatted.ts
  apps/client/src/pages/timetable/page/timetable-content/timetable-content.tsx
  apps/client/src/pages/timetable/page/timetable-page.tsx
  apps/client/src/pages/timetable/utils/index.ts
Labels: 👾 Fix, 한서 🎤

#586 Refactor(design-system): 드래그 핸들러 리팩토링
  packages/design-system/src/components/music-item/music-item.css.ts
  packages/design-system/src/components/music-item/music-item.tsx
Labels: 🛠️ Refactor, 채은 🪕

#588 Refactor(client): Router 개선
  apps/client/src/App.tsx
  apps/client/src/shared/router/router.tsx
  apps/client/src/shared/router/routes/auth-routes.tsx
  apps/client/src/shared/router/routes/fallback-routes.tsx
  apps/client/src/shared/router/routes/global-routes.tsx
  apps/client/src/shared/router/routes/my-page-routes.tsx
  apps/client/src/shared/router/routes/my-record-routes.tsx
  apps/client/src/shared/router/routes/timetable-routes.tsx
Labels: 🛠️ Refactor, 채은 🪕

#590 Fix(client): (QA/6) QA사항 반영
  .vscode/settings.json
  apps/client/src/pages/my-history/components/overview/order-by-button.css.ts
  apps/client/src/pages/my-history/components/record/record-info.css.ts
  apps/client/src/pages/my-history/page/add-songs/add-songs-page.tsx
  apps/client/src/pages/my/hooks/use-logout-mutation.ts
  apps/client/src/pages/my/page/setting/setting.css.ts
  apps/client/src/pages/my/page/setting/setting.tsx
  apps/client/src/pages/search/components/search-result/artist/artist-not-found.css.ts
  apps/client/src/pages/search/components/search-result/artist/artist-not-found.tsx
  apps/client/src/pages/search/hooks/use-search-logic.ts
  apps/client/src/pages/search/page/search-page.tsx
  apps/client/src/pages/search/page/search-result-page.css.ts
  apps/client/src/pages/search/page/search-result-page.tsx
  apps/client/src/pages/timetable/components/onboard/intro-step.tsx
  apps/client/src/pages/timetable/page/empty/empty-festival-section.css.ts
  apps/client/src/shared/apis/search/search-queries.ts
  apps/client/src/shared/constants/query-key.ts
  packages/design-system/src/components/toast/toast.css.ts
  packages/design-system/src/styles/reset.css.ts
Labels: 👾 Fix, 민하 🎸

#593 Fix(client): QA 반영
  apps/client/src/pages/home/components/suggest-performance-section.css.ts
  apps/client/src/pages/my-history/components/setlist-detail/setlist-empty.tsx
  apps/client/src/pages/my-history/page/add-setlist/add-setlist-page.tsx
  apps/client/src/shared/utils/format-date.ts
Labels: 👾 Fix, 민하 🎸

#598 Refactor(design-system): 캐러셀 오버레이 추가
  apps/client/src/pages/timetable/components/festival-selector/festival-selector.tsx
  packages/design-system/src/components/performance-carousel/performance-carousel.tsx
Labels: 🛠️ Refactor, 한서 🎤

#600 Fix(QA): ProgressBar 컴포넌트 아이콘 크기 및 색상 조정, SVG 아이콘 업데이트
  apps/client/public/images/img_onboard_2.svg
  apps/client/public/images/img_onboard_3.svg
  apps/client/public/images/img_onboard_4.svg
  apps/client/public/images/img_onboard_5.svg
  apps/client/public/images/img_onboard_6.svg
  apps/client/src/pages/timetable/components/onboard/progressbar.tsx
  apps/client/src/shared/assets/lotties/confeti-logo-animation.json
  packages/design-system/src/icons/assets/sprites/indicator-default.svg
Labels: 👾 Fix, 지욱 🥁

#602 Fix(client): 온보딩 스크롤 이슈 해결
  apps/client/src/pages/onboarding/components/artist-select.css.ts
  apps/client/src/pages/onboarding/components/onboarding-complete.css.ts
  pnpm-lock.yaml
Labels: 👾 Fix, 채은 🪕

#610 Feat(client): 홈페이지 Chip 카테고리 상단 고정
  apps/client/src/pages/home/components/category-tabs.css.ts
  apps/client/src/pages/home/components/category-tabs.tsx
  apps/client/src/pages/home/constants/menu.ts
  apps/client/src/pages/home/constants/tab.ts
  apps/client/src/pages/home/hooks/use-active-section.ts
  apps/client/src/pages/home/page/home-page.tsx
  apps/client/src/pages/my-history/page/my-history.tsx
  apps/client/src/pages/my/page/setting/setting.css.ts
  apps/client/src/pages/onboarding/components/artist-select.css.ts
  apps/client/src/pages/onboarding/components/onboarding-complete.css.ts
  apps/client/src/pages/timetable/page/timetable-layout.tsx
  apps/client/src/shared/components/navigation-tabs.tsx
  packages/design-system/src/components/header/header.css.ts
  packages/design-system/src/styles/theme.css.ts
  packages/design-system/src/styles/tokens/size.ts
Labels: ✨ Feature, 민하 🎸

#613 Chore: pnpm catalog 적용 및 dependencies 구조 정리
  .github/workflows/build.yml
  .github/workflows/chromatic.yml
  apps/admin/package.json
  apps/client/package.json
  config/eslint/package.json
  package.json
  packages/design-system/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: ✨ Feature, ⚙️ Setting, 민하 🎸

#618 Refactor(client): 이미지 저장 기능 개선
  apps/client/package.json
  apps/client/src/pages/timetable/hooks/use-image-download.ts
  apps/client/src/pages/timetable/page/timetable-content/timetable-content.tsx
  pnpm-lock.yaml
Labels: 🛠️ Refactor, 한서 🎤
