Repository team-confeti/confeti-client, pull requests merged in 2025-03, with the labels that each got.

#307 Refactor(client): 타임테이블 추가 기능 개선
  apps/client/src/pages/time-table/constants/index.ts
  apps/client/src/pages/time-table/hooks/use-festival-selection.ts
  apps/client/src/pages/time-table/hooks/use-timetable-festival-mutation.ts
  apps/client/src/pages/time-table/page/add-festival.tsx
Labels: 🛠️ Refactor, 지욱 🥁

#315 Fix: CODEOWNERS 변경
  .github/CODEOWNERS
Labels: 👾 Fix, 민하 🎸

#318 Feature(client): GA 설정
  apps/client/.env.example
  apps/client/index.html
  apps/client/public/robots.txt
Labels: ✨ Feature, 민하 🎸

#319 Refactor(design-system): display 디자인 토큰 리팩토링
  apps/client/src/pages/my/components/artist/no-artist-section.css.ts
  apps/client/src/pages/my/components/performance/no-performance-section.css.ts
  apps/client/src/pages/performance/components/artist/artist-card.css.ts
  apps/client/src/pages/performance/components/button/more-button.css.ts
  apps/client/src/pages/performance/components/poster/poster.css.ts
  apps/client/src/pages/search/components/artist-info.css.ts
  apps/client/src/pages/search/components/artist-not-found.css.ts
  apps/client/src/pages/search/components/performance-section.css.ts
  apps/client/src/pages/time-table/components/booth-open-box/booth-open-box.css.ts
  apps/client/src/pages/time-table/components/calender/calender.css.ts
  apps/client/src/pages/time-table/components/edit/edit-floating-button.css.ts
  apps/client/src/pages/time-table/components/empty/empty-festival-section.css.ts
  apps/client/src/pages/time-table/components/info/info-button.css.ts
  apps/client/src/pages/time-table/components/stage/stage.css.ts
  apps/client/src/pages/time-table/components/time-table-item/time-table-item.css.ts
  apps/client/src/shared/pages/auth/require-login-section.css.ts
  apps/client/src/shared/pages/error/error.css.ts
  apps/client/src/shared/pages/loading/loading.css.ts
  packages/design-system/src/components/artist-card/artist-card.css.ts
  packages/design-system/src/components/button/button.css.ts
  packages/design-system/src/components/search-bar/search-bar.css.ts
  packages/design-system/src/components/ticketing-carousel/ticketing-carousel.css.ts
  packages/design-system/src/components/toast/toast.css.ts
  packages/design-system/src/styles/global.css.ts
  packages/design-system/src/styles/tokens/display.ts
  packages/design-system/src/styles/tokens/overlay.ts
Labels: 🛠️ Refactor, 지욱 🥁

#320 Fix(client): 라벨 깨짐 현상 해결
  apps/client/src/pages/performance/components/info/info.css.ts
Labels: 👾 Fix, 채은 🪕

#321 Refactor(client): 타임테이블 픽셀 밀림 현상 개선
  apps/client/package.json
  apps/client/src/pages/time-table/components/booth-open-box/booth-open-box.css.ts
  apps/client/src/pages/time-table/components/time-cell/time-cell.css.ts
  apps/client/src/pages/time-table/components/time-table-board/time-table-board.tsx
  apps/client/src/pages/time-table/components/time-table-item/time-table-item.css.ts
  apps/client/src/pages/time-table/components/time-table-item/time-table-item.tsx
  apps/client/src/pages/time-table/utils/index.ts
  pnpm-lock.yaml
Labels: 🛠️ Refactor, 한서 🎤

#324 Refactor(client): 날짜 포맷팅 로직 수정
  apps/client/src/pages/home/page/home.tsx
  apps/client/src/pages/performance/components/info/info.tsx
  apps/client/src/pages/performance/components/summary/summary.tsx
  apps/client/src/pages/search/components/artist-section.tsx
  apps/client/src/pages/search/components/performance-info.tsx
  apps/client/src/pages/search/components/performance-section.tsx
  apps/client/src/pages/time-table/components/booth-open-box/booth-open-box.tsx
  apps/client/src/pages/time-table/components/calender/calender.tsx
  apps/client/src/pages/time-table/components/time-table-board/time-table-board.tsx
  apps/client/src/pages/time-table/components/time-table-item/time-table-item.tsx
  apps/client/src/pages/time-table/hooks/use-data-formatted.ts
  apps/client/src/pages/time-table/utils/index.ts
  apps/client/src/shared/utils/use-format-date.ts
Labels: 🛠️ Refactor, 지욱 🥁

#328 Feat(client): 로그인 페이지 퍼블리싱
  apps/client/src/pages/login/page/login.css.ts
  apps/client/src/pages/login/page/login.tsx
  apps/client/src/pages/my/page/profile/my-profile.tsx
  apps/client/src/shared/constants/path.ts
  apps/client/src/shared/router/lazy.ts
  apps/client/src/shared/router/router.tsx
  packages/design-system/src/components/button/button.css.ts
  packages/design-system/src/components/button/button.tsx
  packages/design-system/src/components/header/header.tsx
  packages/design-system/src/icons/assets/btn_delete_black_20.svg
  packages/design-system/src/icons/assets/confeti_3d_logo2 1.svg
  packages/design-system/src/icons/assets/ic_apple.svg
  packages/design-system/src/icons/assets/ic_kakao.svg
  packages/design-system/src/icons/assets/img_typelogo_big.svg
  packages/design-system/src/icons/src/BtnDeleteBlack20.tsx
  packages/design-system/src/icons/src/Confeti3DLogo21.tsx
  packages/design-system/src/icons/src/IcApple.tsx
  packages/design-system/src/icons/src/IcKakao.tsx
  packages/design-system/src/icons/src/ImgTypelogoBig.tsx
  packages/design-system/src/icons/src/index.ts
  packages/design-system/src/styles/tokens/color.ts
Labels: ✨ Feature, 지욱 🥁

#331 Feat(client): 카카오 로그인,로그아웃 및 public axios 인스턴스 설정
  apps/client/.env.example
  apps/client/package.json
  apps/client/src/pages/home/page/auth/require-login.tsx
  apps/client/src/pages/home/page/home.tsx
  apps/client/src/pages/login/hooks/use-social-login-mutation.ts
  apps/client/src/pages/login/page/login.tsx
  apps/client/src/pages/my/components/profile/user-info.tsx
  apps/client/src/pages/my/hooks/use-logout.ts
  apps/client/src/pages/my/hooks/use-user-info.ts
  apps/client/src/shared/apis/ auth/auth.ts
  apps/client/src/shared/apis/carousel/performances.ts
  apps/client/src/shared/apis/carousel/ticketing.ts
  apps/client/src/shared/apis/config/instance.ts
  apps/client/src/shared/apis/config/interceptor.ts
  apps/client/src/shared/apis/search/search.ts
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/constants/path.ts
  apps/client/src/shared/constants/user-constants.ts
  apps/client/src/shared/mocks/user-data.ts
  apps/client/src/shared/pages/auth/require-login-section.tsx
  apps/client/src/shared/types/login-response.ts
  apps/client/src/shared/utils/check-is-not-logged-in.ts
  apps/client/src/shared/utils/token-handler.ts
  packages/design-system/src/components/header/header.tsx
  pnpm-lock.yaml
Labels: ✨ Feature, 지욱 🥁

#327 Refactor(design-system): Toast 컴포넌트 DX 개선 및 최적화
  apps/client/src/pages/time-table/hooks/use-festival-selection.ts
  packages/design-system/src/components/like-button/like-button.tsx
  packages/design-system/src/components/toast/hooks/use-toast-container.ts
  packages/design-system/src/components/toast/hooks/use-toast.ts
  packages/design-system/src/components/toast/toast-container.css.ts
  packages/design-system/src/components/toast/toast-container.tsx
  packages/design-system/src/components/toast/toast.css.ts
  packages/design-system/src/components/toast/toast.stories.tsx
  packages/design-system/src/components/toast/toast.tsx
  packages/design-system/src/components/toast/types/index.ts
  packages/design-system/src/components/toast/types/type.ts
  packages/design-system/src/components/toast/utils/constants.ts
  packages/design-system/src/components/toast/utils/event-manager.ts
  packages/design-system/src/components/toast/utils/eventManager.ts
  packages/design-system/src/components/toast/utils/toast.ts
  packages/design-system/src/icons/src/IcToastInfo24.tsx
Labels: ✨ Feature, 🛠️ Refactor, 민하 🎸

#342 Feat(design-system): 티켓팅 카드 컴포넌트 구현
  apps/client/public/images/img_dday01.svg
  apps/client/public/images/img_dday02.svg
  apps/client/public/images/img_dday03.svg
  apps/client/public/images/img_dday04.svg
  apps/client/public/images/img_dday05.svg
  apps/client/src/pages/home/page/home.css.ts
  apps/client/src/pages/home/page/home.tsx
  apps/client/src/shared/utils/format-date.ts
  packages/design-system/src/components/index.ts
  packages/design-system/src/components/ticketing-carousel/info-button/info-button.css.ts
  packages/design-system/src/components/ticketing-carousel/info-button/info-button.stories.tsx
  packages/design-system/src/components/ticketing-carousel/info-button/info-button.tsx
  packages/design-system/src/components/ticketing/hooks/use-carousel-data.ts
  packages/design-system/src/components/ticketing/hooks/use-carousel-slide.ts
  packages/design-system/src/components/ticketing/hooks/use-control-time.ts
  packages/design-system/src/components/ticketing/hooks/use-data-format.ts
  packages/design-system/src/components/ticketing/mocks/bottom-banner-data.ts
  packages/design-system/src/components/ticketing/progress-bar/progress-bar.css.ts
  packages/design-system/src/components/ticketing/progress-bar/progress-bar.stories.tsx
  packages/design-system/src/components/ticketing/progress-bar/progress-bar.tsx
  packages/design-system/src/components/ticketing/ticketing-card.css.ts
  packages/design-system/src/components/ticketing/ticketing-card.stories.tsx
  packages/design-system/src/components/ticketing/ticketing-card.tsx
  packages/design-system/src/components/ticketing/ticketing-carousel.css.ts
  packages/design-system/src/components/ticketing/ticketing-carousel.stories.tsx
  packages/design-system/src/components/ticketing/ticketing-carousel.tsx
Labels: ✨ Feature, 지욱 🥁

#351 Fix(client): my 아티스트 조회 api url 수정 반영
  apps/client/src/shared/apis/like/like.ts
  apps/client/src/shared/apis/user/user.ts
  apps/client/src/shared/constants/api.ts
Labels: 👾 Fix, 지욱 🥁

#346 Feat(client): 액세스 토큰 만료 시 토큰 갱신 로직 api
  apps/client/src/pages/login/hooks/use-social-login-mutation.ts
  apps/client/src/pages/my/hooks/use-logout.ts
  apps/client/src/shared/apis/confeti-detail/performance.ts
  apps/client/src/shared/apis/config/interceptor.ts
  apps/client/src/shared/constants/api.ts
  apps/client/src/shared/types/api.ts
  apps/client/src/shared/types/login-response.ts
  apps/client/src/shared/utils/token-handler.ts
Labels: ✨ Feature, 지욱 🥁

#352 Feat(design-system): Avatar 컴포넌트 구현
  packages/design-system/src/components/avatar/avatar.css.ts
  packages/design-system/src/components/avatar/avatar.stories.tsx
  packages/design-system/src/components/avatar/avatar.tsx
  packages/design-system/src/components/index.ts
  packages/design-system/src/icons/assets/cmp_profile_non.svg
  packages/design-system/src/icons/src/CmpProfileNon.tsx
  packages/design-system/src/icons/src/index.ts
  packages/design-system/src/styles/index.ts
  packages/design-system/src/styles/tokens/screen.ts
Labels: ✨ Feature, 민하 🎸
